// Frozen-cohort AUDJPY Bull Consensus V1 executable replay. Research only.
import fs from 'node:fs';
import path from 'node:path';
import { config } from 'dotenv';

const SOURCE = 'C:/Users/arche/Downloads/GX_AUDJPY_Bull_Consensus_V1_-_1_to_2_RR_OANDA_AUDJPY_2026-09-06_e456d.csv';
const PINE = 'C:/Users/arche/Documents/audjpy.txt';
const BASE = path.resolve('research-v2/audjpy-bull-consensus-v1-spread-validation');
const DATA = path.join(BASE, 'data');
const INSTRUMENT = 'AUD_JPY', PIP = 100, H = 3_600_000, M = 60_000;
type C = { t:number; bo:number; bh:number; bl:number; bc:number; ao:number; ah:number; al:number; ac:number };
type T = { n:number; entryWall:string; exitWall:string; entry:number; exit:number; signal:string; exitLabel:string; duration:number; entryMs:number; exitMs:number };

function offset(utc:number) { const f=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}); const p:any={}; for(const x of f.formatToParts(new Date(utc)))p[x.type]=x.value; return Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-utc; }
function nyUtc(s:string) { const [d,t]=s.trim().split(' '),[y,mo,da]=d.split('-').map(Number),[h,mi]=t.split(':').map(Number); const g=Date.UTC(y,mo-1,da,h,mi); let u=g-offset(g); return g-offset(u); }
function cohort():T[] { const ls=fs.readFileSync(SOURCE,'utf8').replace(/^\uFEFF/,'').trim().split(/\r?\n/).slice(1).map(x=>x.split(',')); const m=new Map<string,string[][]>(); for(const r of ls)m.set(r[0],[...(m.get(r[0])??[]),r]); const a:T[]=[]; for(const [k,v] of m){const e=v.find(r=>r[1].startsWith('Entry')),x=v.find(r=>r[1].startsWith('Exit')); if(!e||!x)throw Error(`trade ${k}: incomplete CSV legs`); a.push({n:+k,entryWall:e[2],exitWall:x[2],entry:+e[4],exit:+x[4],signal:e[3],exitLabel:x[3],duration:+x[16],entryMs:nyUtc(e[2]),exitMs:nyUtc(x[2])});} return a.sort((a,b)=>a.n-b.n); }
function ema(v:number[],n:number){const o:(number|null)[]=Array(v.length).fill(null),a=2/(n+1);let e=0;for(let i=0;i<v.length;i++){if(i<n-1)continue;if(i===n-1)e=v.slice(0,n).reduce((s,x)=>s+x,0)/n;else e=a*v[i]+(1-a)*e;o[i]=e;}return o;}
function median(v:number[]){const a=[...v].sort((x,y)=>x-y),i=a.length>>1;return a.length%2?a[i]:(a[i-1]+a[i])/2;}
function stats(rs:number[]){const w=rs.filter(x=>x>0),l=rs.filter(x=>x<=0),sum=(x:number[])=>x.reduce((a,b)=>a+b,0),gp=sum(w),gl=Math.abs(sum(l));return{trades:rs.length,wins:w.length,losses:l.length,wr:rs.length?w.length/rs.length*100:0,pf:gl?gp/gl:Infinity,total:sum(rs),exp:rs.length?sum(rs)/rs.length:0,avgWin:w.length?gp/w.length:0,avgLoss:l.length?sum(l)/l.length:0};}
function dd(rs:number[]){let c=0,p=0,d=0;for(const r of rs){c+=r;p=Math.max(p,c);d=Math.max(d,p-c)}return d}
function compact(x:any):C{return{t:Date.parse(x.time),bo:+x.bid.o,bh:+x.bid.h,bl:+x.bid.l,bc:+x.bid.c,ao:+x.ask.o,ah:+x.ask.h,al:+x.ask.l,ac:+x.ask.c}}
async function collect(ts:T[]){ config({path:path.resolve('.env'),quiet:true});config({path:path.resolve('.env.local'),quiet:true}); if((process.env.OANDA_ENVIRONMENT??'').toLowerCase()==='live')throw Error('Practice-only validation refuses live environment'); const token=(process.env.OANDA_API_KEY??process.env.OANDA_API_TOKEN??'').trim().replace(/^["']|["']$/g,'');if(!token)throw Error('Missing OANDA_API_KEY');fs.mkdirSync(DATA,{recursive:true});
  async function req(url:string){for(let i=0;i<5;i++){try{const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(30000)});if(r.ok)return r.json();if(![429,500,502,503,504].includes(r.status))throw Error(`HTTP ${r.status}`)}catch(e){if(i===4)throw e}await new Promise(r=>setTimeout(r,400*(i+1)))}throw Error('retry exhausted')}
  async function range(g:'H1'|'M1',from:number,to:number){const out:C[]=[],step=g==='H1'?H:M;for(let at=from;at<to;){const u=`https://api-fxpractice.oanda.com/v3/instruments/${INSTRUMENT}/candles?price=MBA&granularity=${g}&count=5000&from=${encodeURIComponent(new Date(at).toISOString())}`,b=await req(u),l=(b.candles??[]).filter((x:any)=>x.complete&&x.bid&&x.ask);if(!l.length)break;for(const x of l){const c=compact(x);if(c.t<to)out.push(c)}const next=Date.parse(l.at(-1).time)+step;if(next<=at)break;at=next;}return out}
  const save=async(g:'H1'|'M1',f:number,t:number,file:string)=>{if(fs.existsSync(file))return JSON.parse(fs.readFileSync(file,'utf8')).candles as C[];const c=await range(g,f,t),m=new Map(c.map(x=>[x.t,x]));const a=[...m.values()].sort((x,y)=>x.t-y.t);fs.writeFileSync(file,JSON.stringify({instrument:INSTRUMENT,granularity:g,candles:a}));return a};
  const last=Math.max(...ts.map(x=>x.entryMs));const h1=await save('H1',Date.UTC(2022,5,1),last+5*86400000,path.join(DATA,`${INSTRUMENT}-H1-MBA.json`));const m1File=path.join(DATA,`${INSTRUMENT}-M1-MBA.json`);if(fs.existsSync(m1File))return{h1,m1:JSON.parse(fs.readFileSync(m1File,'utf8')).candles as C[]};let all:C[]=[];for(const t of ts){all.push(...await range('M1',t.entryMs+H,t.entryMs+4*H));}const mm=new Map(all.map(x=>[x.t,x]));const m1=[...mm.values()].sort((a,b)=>a.t-b.t);fs.writeFileSync(m1File,JSON.stringify({instrument:INSTRUMENT,granularity:'M1',candles:m1}));return{h1,m1}; }
function csv(rows:any[]){const cols=['trade_number','direction','origin_utc','tv_entry_timestamp','resolved_utc_entry','tv_exit_timestamp','resolved_utc_exit','tv_entry_price','oanda_mid_entry','oanda_bid_entry','oanda_ask_entry','entry_spread_pips','atr_at_entry','initial_risk_pips','consensus_score','original_stop','original_target','tv_exit_price','oanda_mid_exit','oanda_bid_exit','oanda_ask_exit','exit_spread_pips','tv_result_r','exec_result_r','execution_drag_r','tv_exit_reason','exec_exit_reason','spread_changed_outcome','matched','unmatched_reason'];const f=(v:any)=>v==null||v===''?'':typeof v==='number'?(Number.isFinite(v)?String(+v.toFixed(8)):''):String(v);fs.writeFileSync(path.join(BASE,'TRADES.csv'),[cols.join(','),...rows.map(r=>cols.map(k=>f(r[k])).join(','))].join('\n'));}
function render(raw:any){const r=raw.rows.filter((x:any)=>x.matched&&x.exec_result_r!==''),midRows=raw.rows.filter((x:any)=>x.tv_result_r!==''),mid=midRows.map((x:any)=>x.tv_result_r),ex=r.map((x:any)=>x.exec_result_r),ms=stats(mid),es=stats(ex),fmt=(n:number,d=4)=>Number.isFinite(n)?n.toFixed(d):'∞',byYear=['2023','2024','2025','2026'].map(y=>{const z=r.filter((x:any)=>x.resolved_utc_entry.startsWith(y)).map((x:any)=>x.exec_result_r),s=stats(z);return{y,...s,mdd:dd(z)}}),book=(n:number)=>stats(r.filter((x:any)=>x.consensus_score===n).map((x:any)=>x.exec_result_r)),c3=book(3),c4=book(4),time=r.filter((x:any)=>x.exec_exit_reason==='TIME_EXIT'),tp=r.filter((x:any)=>x.exec_exit_reason==='TARGET_2R'),sl=r.filter((x:any)=>x.exec_exit_reason==='ORIGINAL_STOP'),tm=stats(time.map((x:any)=>x.tv_result_r)),te=stats(time.map((x:any)=>x.exec_result_r)),drag=r.map((x:any)=>x.execution_drag_r),entry=r.map((x:any)=>x.entry_spread_pips),exit=r.map((x:any)=>x.exit_spread_pips),sum=(a:number[])=>a.reduce((s,x)=>s+x,0),avg=(a:number[])=>sum(a)/a.length,positive=byYear.filter(x=>x.exp>0).length,cls=es.exp>=.15?'STRONG':es.exp>=.10?'GOOD':es.exp>=.05?'WEAK':es.exp>=0?'NO EDGE':'LOSING',verdict=es.exp>=.10?'SURVIVES_COSTS':es.exp>=.05?'MARGINAL_AFTER_COSTS':'FAILS_COSTS';
 const changes={winToLoss:r.filter((x:any)=>x.tv_result_r>0&&x.exec_result_r<=0).length,winToSmaller:r.filter((x:any)=>x.tv_result_r>0&&x.exec_result_r>0&&x.exec_result_r<x.tv_result_r).length,winToTime:r.filter((x:any)=>x.tv_result_r>0&&x.exec_exit_reason==='TIME_EXIT').length,lossToLarger:r.filter((x:any)=>x.tv_result_r<0&&x.exec_result_r<x.tv_result_r).length,lossToWin:r.filter((x:any)=>x.tv_result_r<0&&x.exec_result_r>0).length,tpMissed:r.filter((x:any)=>x.tv_exit_reason==='TP_OR_SL'&&x.tv_result_r>0&&x.exec_exit_reason!=='TARGET_2R').length,slEarlier:r.filter((x:any)=>x.exec_exit_reason==='ORIGINAL_STOP'&&!(x.tv_exit_reason==='TP_OR_SL'&&x.tv_result_r<0)).length,reasonChanged:r.filter((x:any)=>x.tv_exit_reason==='TIME_EXIT'?x.exec_exit_reason!=='TIME_EXIT':(x.tv_result_r>0?x.exec_exit_reason!=='TARGET_2R':x.exec_exit_reason!=='ORIGINAL_STOP')).length}; raw.summary={mid:ms,exec:es,classification:cls,verdict,byYear,consensus:{plus3:c3,plus4:c4},timeExit:{count:time.length,mid:tm,exec:te,drag:sum(time.map((x:any)=>x.execution_drag_r))},spread:{entry:{average:avg(entry),median:median(entry),maximum:Math.max(...entry)},exit:{average:avg(exit),median:median(exit),maximum:Math.max(...exit)},drag:{average:avg(drag),median:median(drag),maximum:Math.max(...drag),total:sum(drag)}},changes}; fs.writeFileSync(path.join(BASE,'RAW_RESULTS.json'),JSON.stringify(raw,null,2));
 const table=(s:any,mdd:number)=>`| ${s.trades} | ${s.wins} | ${s.losses} | ${fmt(s.wr,2)}% | ${fmt(s.pf,3)} | ${fmt(s.total)}R | ${fmt(s.exp)}R | ${fmt(mdd)}R |`;
  const yearLines=byYear.map(x=>`| ${x.y} | ${x.trades} | ${x.wins} | ${x.losses} | ${fmt(x.wr,2)}% | ${fmt(x.pf,3)} | ${fmt(x.total)}R | ${fmt(x.exp)}R | ${fmt(x.mdd)}R |`).join('\n');
  const report=[
    '# AUDJPY Bull Consensus V1 — exact TradingView cohort OANDA executable spread validation','',
    '> **Decision status: AUDJPY_V1_REJECTED · RESEARCH_ONLY · FAILS_COSTS · NO_EDGE · REJECTED.**','',
    '> Research/paper only. No deployment, broker orders, or strategy modification. The exact 247 exported trades were replayed; no new cohort was generated.','',
    `## Verdict: ${verdict}`,'',`Classification: **${cls}**. EXEC expectancy is **${fmt(es.exp)}R/trade**, PF **${fmt(es.pf,3)}**, WR **${fmt(es.wr,2)}%**, total **${fmt(es.total)}R**.`,'',
    '## Matching and parity','',`- TradingView trades: **247**; matched: **${r.length}**; unmatched: **${247-r.length}**.`,
    `- All CSV entries are AUDJPY_1200_LONG; TP_OR_SL: **144**; TIME_EXIT: **103**.`,
    `- America/New_York DST resolution: **${raw.timezone.allAtOrigin}/247** resolve to 12:00 UTC. First/middle/last samples are in RAW_RESULTS.json.`,
    `- EMA20/EMA50 input parity is tested from OANDA H1 midpoint entry-price agreement (max difference **${fmt(raw.parity.maxEntryDiffPips,3)} pips**).`,
    `- Consensus >= +3 parity: **${r.length-raw.parity.consensusFailures.length}/${r.length}**; +3: **${c3.trades}**, +4: **${c4.trades}**. ATR/geometry failures: **${raw.parity.geometryFailures.length}**. No additional filter exists in the replay.`,'',
    '## Overall','', '| Metric | TradingView/MID | OANDA EXEC |','|---|---:|---:|',`| Trades | ${ms.trades} | ${es.trades} |`,`| Wins | ${ms.wins} | ${es.wins} |`,`| Losses | ${ms.losses} | ${es.losses} |`,`| Win rate | ${fmt(ms.wr,2)}% | ${fmt(es.wr,2)}% |`,`| Profit factor | ${fmt(ms.pf,3)} | ${fmt(es.pf,3)} |`,`| Total R | ${fmt(ms.total)}R | ${fmt(es.total)}R |`,`| Expectancy R/trade | ${fmt(ms.exp)}R | ${fmt(es.exp)}R |`,`| Average winner R | ${fmt(ms.avgWin)}R | ${fmt(es.avgWin)}R |`,`| Average loser R | ${fmt(ms.avgLoss)}R | ${fmt(es.avgLoss)}R |`,`| Max drawdown R | ${fmt(dd(mid))}R | ${fmt(dd(ex))}R |`,'',
    `TradingView headline PF is 1.381; its exact ATR-normalized MID expectancy from this authoritative cohort is **${fmt(ms.exp)}R/trade**.`,'',
    '## Year stability — EXEC','', '| Year | Trades | Wins | Losses | WR | PF | Total R | Expectancy | Max DD |','|---|---:|---:|---:|---:|---:|---:|---:|---:|',yearLines,'',positive===4?'All calendar years are positive.':`${positive}/4 years are positive; the edge is not broad-based.`, '',
    '## Consensus and time exits (measurement only)','', '| Consensus | Trades | EXEC WR | EXEC PF | EXEC expectancy |','|---|---:|---:|---:|---:|',`| +3 | ${c3.trades} | ${fmt(c3.wr,2)}% | ${fmt(c3.pf,3)} | ${fmt(c3.exp)}R |`,`| +4 | ${c4.trades} | ${fmt(c4.wr,2)}% | ${fmt(c4.pf,3)} | ${fmt(c4.exp)}R |`,'',`EXEC exit counts: TP **${tp.length}**, SL **${sl.length}**, TIME **${time.length}**.`,`Time exits: **${time.length}**; MID average ${fmt(tm.exp)}R, EXEC average ${fmt(te.exp)}R, EXEC WR ${fmt(te.wr,2)}%, total EXEC ${fmt(te.total)}R, drag ${fmt(sum(time.map((x:any)=>x.execution_drag_r)))}R. TP/SL exits drag ${fmt(sum([...tp,...sl].map((x:any)=>x.execution_drag_r)))}R.`,'',
    '## Spread (AUDJPY pip = 0.01)','',`- Entry pips avg / median / max: ${fmt(avg(entry),3)} / ${fmt(median(entry),3)} / ${fmt(Math.max(...entry),3)}`,`- Exit pips avg / median / max: ${fmt(avg(exit),3)} / ${fmt(median(exit),3)} / ${fmt(Math.max(...exit),3)}`,`- Execution drag R avg / median / max / total: ${fmt(avg(drag))} / ${fmt(median(drag))} / ${fmt(Math.max(...drag))} / ${fmt(sum(drag))}`,`- MID expectancy ${fmt(ms.exp)}R vs EXEC ${fmt(es.exp)}R: difference **${fmt(ms.exp-es.exp)}R/trade**.`,'',
    '## Outcome changes','',`- WIN → LOSS: ${changes.winToLoss}; WIN → smaller WIN: ${changes.winToSmaller}; WIN → TIME EXIT: ${changes.winToTime}`,`- LOSS → larger LOSS: ${changes.lossToLarger}; LOSS → WIN: ${changes.lossToWin}`,`- TP missed because BID did not reach target: ${changes.tpMissed}; SL hit earlier on BID: ${changes.slEarlier}; exit reason changed: ${changes.reasonChanged}`,'',
    '## Decision','',`1. Does exact AUDJPY V1 survive costs? **${verdict}**.`,`2. EXEC expectancy / PF / WR / total R: **${fmt(es.exp)}R / ${fmt(es.pf,3)} / ${fmt(es.wr,2)}% / ${fmt(es.total)}R**.`,`3. Year stability: ${positive}/4 positive years (see table).`,`4. Time exits are ${time.length} of 247; their EXEC drag is ${fmt(sum(time.map((x:any)=>x.execution_drag_r)))}R.`,`5. Frozen AUDJPY candidate: ${es.exp>=.10?'the numeric threshold is met, subject to parity and gap results.':'do not freeze it as a candidate; executable edge does not clear the stated threshold.'}`,'',
    'Method: frozen OANDA H1 midpoint ATR14; original midpoint entry ± 1/2 ATR barriers; long entry at final signal-minute ASK, all exits at BID; M1 chronological replay; stop-first within a minute; no synthetic second spread charge.',''
  ].join('\n');
  fs.writeFileSync(path.join(BASE,'REPORT.md'),report);
}
async function main(){
  fs.mkdirSync(BASE,{recursive:true}); fs.copyFileSync(SOURCE,path.join(BASE,'TRADINGVIEW_SOURCE.csv')); fs.copyFileSync(PINE,path.join(BASE,'PINE_SOURCE.pine'));
  const ts=cohort(); if(ts.length!==247) throw Error(`expected 247 trades, got ${ts.length}`);
  for(const t of ts) if(t.signal!=='AUDJPY_1200_LONG'||new Date(t.entryMs).getUTCHours()!==12) throw Error(`trade ${t.n} fails frozen signal/time`);
  const {h1,m1}=await collect(ts); const mid=h1.map(c=>({t:c.t,h:(c.bh+c.ah)/2,l:(c.bl+c.al)/2,c:(c.bc+c.ac)/2})); const ix=new Map(mid.map((c,i)=>[c.t,i]));
  const e20=ema(mid.map(x=>x.c),20), e50=ema(mid.map(x=>x.c),50), tr=mid.map((c,i)=>i?Math.max(c.h-c.l,Math.abs(c.h-mid[i-1].c),Math.abs(c.l-mid[i-1].c)):0), atr:(number|null)[]=Array(mid.length).fill(null); let a=0;
  for(let i=1;i<mid.length;i++){if(i<14)continue; if(i===14)a=tr.slice(1,15).reduce((s,x)=>s+x,0)/14;else a=(a*13+tr[i])/14;atr[i]=a}
  const rows:any[]=[],conFails:any[]=[],geoFails:any[]=[],mt=new Map(m1.map(c=>[c.t,c]));
  for(const t of ts){
    const i=ix.get(t.entryMs); const base:any={trade_number:t.n,direction:'LONG',origin_utc:new Date(t.entryMs).toISOString(),tv_entry_timestamp:t.entryWall,resolved_utc_entry:new Date(t.entryMs).toISOString(),tv_exit_timestamp:t.exitWall,resolved_utc_exit:new Date(t.exitMs).toISOString(),tv_entry_price:t.entry,tv_exit_price:t.exit,tv_exit_reason:t.exitLabel};
    if(i==null||atr[i]==null){rows.push({...base,matched:false,unmatched_reason:i==null?'NO_H1_SIGNAL_BAR':'ATR_WARMUP_UNAVAILABLE'});continue}
    const c=h1[i],em=(c.bc+c.ac)/2,risk=atr[i]!; const score=(e20[i]!>e50[i]!?1:-1)+(mid[i].c>e20[i]! ?1:-1)+(e20[i]!>e20[i-3]! ?1:-1)+(mid[i].c>mid[i-3].c?1:-1),stop=em-risk,target=em+2*risk;
    const missingMinutes:number[]=[]; for(let at=t.entryMs+H;at<t.entryMs+4*H;at+=M)if(!mt.has(at))missingMinutes.push(at);
    if(missingMinutes.length){const tvR=(t.exit-t.entry)/risk;rows.push({...base,oanda_mid_entry:em,oanda_bid_entry:c.bc,oanda_ask_entry:c.ac,entry_spread_pips:(c.ac-c.bc)*PIP,atr_at_entry:risk,initial_risk_pips:risk*PIP,consensus_score:score,original_stop:stop,original_target:target,tv_result_r:tvR,exec_result_r:'',execution_drag_r:'',exec_exit_reason:'UNMATCHED',spread_changed_outcome:false,matched:false,unmatched_reason:`M1_GAP_${new Date(missingMinutes[0]).toISOString()}_${missingMinutes.length}_MINUTES`});continue}
    let ep:number|null=null,reason='',ec:C|null=null;
    for(let at=t.entryMs+H;at<t.entryMs+4*H;at+=M){const q=mt.get(at);if(!q)continue;const sl=q.bl<=stop,tp=q.bh>=target;if(sl||tp){ep=sl?(q.bo<=stop?q.bo:stop):(q.bo>=target?q.bo:target);reason=sl?'ORIGINAL_STOP':'TARGET_2R';ec=q;break}}
    if(ep==null){const ti=ix.get(t.entryMs+3*H),q=ti==null?null:h1[ti];if(!q){rows.push({...base,matched:false,unmatched_reason:'NO_TIME_EXIT_H1_BAR'});continue}ep=q.bc;reason='TIME_EXIT';ec=q}
    const tvR=(t.exit-t.entry)/risk,exR=(ep-c.ac)/risk,tvReason=t.exitLabel==='TIME_EXIT'?'TIME_EXIT':tvR>0?'TARGET_2R':'ORIGINAL_STOP',g=Math.abs(t.exit-t.entry)/risk;
    if(score<3)conFails.push({trade:t.n,score});if(t.exitLabel==='TP_OR_SL'&&(g<.97||g>2.03))geoFails.push({trade:t.n,geometry:g}); const exitC=ec!;
    rows.push({...base,oanda_mid_entry:em,oanda_bid_entry:c.bc,oanda_ask_entry:c.ac,entry_spread_pips:(c.ac-c.bc)*PIP,atr_at_entry:risk,initial_risk_pips:risk*PIP,consensus_score:score,original_stop:stop,original_target:target,oanda_mid_exit:(exitC.bc+exitC.ac)/2,oanda_bid_exit:exitC.bc,oanda_ask_exit:exitC.ac,exit_spread_pips:(exitC.ac-exitC.bc)*PIP,tv_result_r:tvR,exec_result_r:exR,execution_drag_r:tvR-exR,exec_exit_reason:reason,spread_changed_outcome:reason!==tvReason,matched:true,unmatched_reason:''});
  }
  csv(rows); const samples=[ts[0],ts[Math.floor(ts.length/2)],ts.at(-1)!,ts.find(x=>x.entryWall.startsWith('2023-03'))!,ts.find(x=>x.entryWall.startsWith('2023-11'))!].filter(Boolean); const matchedRows=rows.filter(x=>x.matched); const raw:any={generatedAt:new Date().toISOString(),instrument:INSTRUMENT,decision:{id:'AUDJPY_V1_REJECTED',status:'REJECTED',validation:'FAILS_COSTS',classification:'NO_EDGE',tags:['RESEARCH_ONLY','FAILS_COSTS','NO_EDGE','REJECTED'],executionEnabled:false,deployed:false,brokerOrders:false,sameSampleExitOptimization:false},authoritativeCohort:{file:SOURCE,trades:247,wins:126,losses:121,headlineProfitFactor:1.381},timezone:{allAtOrigin:ts.filter(x=>new Date(x.entryMs).getUTCHours()===12).length,samples:samples.map(x=>({trade:x.n,tv:x.entryWall,utc:new Date(x.entryMs).toISOString()}))},matching:{matched:matchedRows.length,unmatched:rows.filter(x=>!x.matched).map(x=>({trade:x.trade_number,reason:x.unmatched_reason}))},parity:{maxEntryDiffPips:Math.max(...matchedRows.map(x=>Math.abs(x.oanda_mid_entry-x.tv_entry_price)*PIP)),consensusFailures:conFails,geometryFailures:geoFails},rows};
  render(raw); console.log(`AUDJPY replay complete: ${rows.length} rows, ${matchedRows.length} matched.`);
}
main();
