import assert from "node:assert/strict";
import { replayExit, forcedExit, atrOnlyRegime, type Plan } from "./research-additional-pairs-v1";
import { evaluateBreakout, DEFAULT_BREAKOUT_CONFIG } from "../src/lib/strategy/strategies/breakout";
import { calculateAtrValues } from "../src/lib/strategy/indicators";
import { classifyRegime } from "../src/lib/strategy/regime";
import type { ResearchCandle } from "../src/lib/oanda/client";
import type { Candle } from "../src/types/forex";
import type { StrategyEvaluationInput } from "../src/lib/strategy/types";
const t = Date.parse("2024-06-03T12:00:00Z");
const plan: Plan = { direction: "long", entry: 100, stop: 99, target: 102, decision: t };
const q = (open: number, low: number, high: number, close = open) => ({ open, low, high, close });
const bar = (bid: ReturnType<typeof q>, ask = bid, at = t): ResearchCandle => ({ time: new Date(at).toISOString(), mid: bid, bid, ask, volume: 10, complete: true });
assert.equal(replayExit(plan, [bar(q(100, 98, 103))], 0).reason, "SL");
assert.equal(replayExit(plan, [bar(q(100, 98, 103))], 0).ambiguous, true);
assert.equal(replayExit(plan, [bar(q(100, 99.5, 102))], 0).resultR, 2);
assert.equal(replayExit(plan, [bar(q(98, 97, 100))], 0).resultR, -2);
assert.equal(replayExit(plan, [bar(q(100, 99.5, 101.9), q(100.2, 99.7, 102.1))], 0).reason, "CENSORED", "Long cannot exit on ask target");
const short: Plan = { ...plan, direction: "short", stop: 101, target: 98 };
assert.equal(replayExit(short, [bar(q(99.8, 97.9, 100.3), q(100, 98.1, 100.5))], 0).reason, "CENSORED", "Short cannot exit on bid target");
assert.equal(replayExit(short, [bar(q(100, 97, 102), q(100.1, 97.1, 102.1))], 0).reason, "SL");
assert.equal(replayExit(plan, [bar(q(100, 99.5, 100.5), undefined, t + 900_000)], 0).reason, "DATA_GAP");
assert.equal(replayExit(plan, [bar(q(100, 90, 110), undefined, t - 900_000), bar(q(100, 99.5, 102))], 0).reason, "TP", "Signal-bar excursions excluded");
assert.equal(forcedExit(t, Date.parse("2024-06-03T20:45:00Z")), true);
assert.equal(forcedExit(t, Date.parse("2024-06-03T20:30:00Z")), false);
assert.equal(forcedExit(Date.parse("2024-01-03T12:00:00Z"), Date.parse("2024-01-03T21:45:00Z")), true);
assert.equal(forcedExit(t, Date.parse("2024-06-04T20:45:00Z")), false);
const late = Date.parse("2024-06-03T20:30:00Z");
assert.equal(replayExit({ ...plan, decision: late }, [bar(q(100, 99.5, 101, 100.5), undefined, late)], 0).resultR, .5);
const candles: Candle[] = Array.from({ length: 500 }, (_, i) => ({ time: new Date(t - (500 - i) * 900_000).toISOString(), open: 1.35, high: 1.3502, low: 1.3498, close: 1.35, complete: true, volume: 20 }));
for (let i = 0; i < 499; i += 2) candles[i] = { ...candles[i], open: 1.3503, close: 1.3503, high: 1.3505, low: 1.3501 };
candles[499] = { ...candles[499], high: 1.3515, close: 1.3513 };
const input: StrategyEvaluationInput = { instrument: "USD_CAD", accountBalance: 100, accountCurrency: "USD", dataSource: "oanda", candles15m: candles, candles1h: candles, candles4h: candles,
  bid: 1.35125, ask: 1.35135, spreadPips: 1, marketOpen: true, calendarConnected: false, highImpactNewsWithinMinutes: null, evaluatedAt: new Date(t).toISOString(), evaluationMode: "historical_replay" };
const atr = calculateAtrValues(candles, 14).at(-1)!;
const fast = evaluateBreakout(input, atrOnlyRegime(atr, "USD_CAD", input.evaluatedAt!), DEFAULT_BREAKOUT_CONFIG);
const reference = evaluateBreakout(input, classifyRegime("USD_CAD", candles, input.evaluatedAt!), DEFAULT_BREAKOUT_CONFIG);
assert.equal(fast.status, "valid", fast.qualifyReason);
assert.deepEqual([fast.status, fast.direction, fast.entry, fast.stop, fast.target], [reference.status, reference.direction, reference.entry, reference.stop, reference.target]);
assert.equal(fast.entry, input.ask);
assert.ok(Math.abs((fast.target! - fast.entry!) / (fast.entry! - fast.stop!) - 2) < 1e-9);
const withFuture = [...candles, { ...candles.at(-1)!, close: 100, high: 100 }];
assert.equal(calculateAtrValues(withFuture, 14)[499], atr, "Full-array precompute is causal");
assert.equal(evaluateBreakout({ ...input, evaluationMode: "live" }, atrOnlyRegime(atr, "USD_CAD", input.evaluatedAt!), DEFAULT_BREAKOUT_CONFIG).status, "no_setup", "Live missing news remains blocked");
console.log("Additional-pair replay: bid/ask, ambiguity, gap, no-lookahead, DST, entry parity and news-boundary tests passed.");
