-- Every pair the app offers needs an instruments row: manual entries,
-- notifications and research rows reference instruments(code), so an entry on
-- a pair missing here (AUD/CAD and 52 others) failed with a foreign-key error.
-- Generated from frontend/src/lib/instruments/catalog.ts; existing rows keep
-- their values.

INSERT INTO instruments(code, display_name, price_precision)
VALUES
  ('AUD_CAD', 'AUD/CAD', 5),
  ('AUD_CHF', 'AUD/CHF', 5),
  ('AUD_HKD', 'AUD/HKD', 5),
  ('AUD_JPY', 'AUD/JPY', 3),
  ('AUD_NZD', 'AUD/NZD', 5),
  ('AUD_SGD', 'AUD/SGD', 5),
  ('AUD_USD', 'AUD/USD', 5),
  ('CAD_CHF', 'CAD/CHF', 5),
  ('CAD_HKD', 'CAD/HKD', 5),
  ('CAD_JPY', 'CAD/JPY', 3),
  ('CAD_SGD', 'CAD/SGD', 5),
  ('CHF_HKD', 'CHF/HKD', 5),
  ('CHF_JPY', 'CHF/JPY', 3),
  ('CHF_ZAR', 'CHF/ZAR', 5),
  ('EUR_AUD', 'EUR/AUD', 5),
  ('EUR_CAD', 'EUR/CAD', 5),
  ('EUR_CHF', 'EUR/CHF', 5),
  ('EUR_CZK', 'EUR/CZK', 5),
  ('EUR_DKK', 'EUR/DKK', 5),
  ('EUR_GBP', 'EUR/GBP', 5),
  ('EUR_HKD', 'EUR/HKD', 5),
  ('EUR_HUF', 'EUR/HUF', 3),
  ('EUR_JPY', 'EUR/JPY', 3),
  ('EUR_NOK', 'EUR/NOK', 5),
  ('EUR_NZD', 'EUR/NZD', 5),
  ('EUR_PLN', 'EUR/PLN', 5),
  ('EUR_SEK', 'EUR/SEK', 5),
  ('EUR_SGD', 'EUR/SGD', 5),
  ('EUR_TRY', 'EUR/TRY', 5),
  ('EUR_USD', 'EUR/USD', 5),
  ('EUR_ZAR', 'EUR/ZAR', 5),
  ('GBP_AUD', 'GBP/AUD', 5),
  ('GBP_CAD', 'GBP/CAD', 5),
  ('GBP_CHF', 'GBP/CHF', 5),
  ('GBP_HKD', 'GBP/HKD', 5),
  ('GBP_JPY', 'GBP/JPY', 3),
  ('GBP_NZD', 'GBP/NZD', 5),
  ('GBP_PLN', 'GBP/PLN', 5),
  ('GBP_SGD', 'GBP/SGD', 5),
  ('GBP_USD', 'GBP/USD', 5),
  ('GBP_ZAR', 'GBP/ZAR', 5),
  ('HKD_JPY', 'HKD/JPY', 5),
  ('NZD_CAD', 'NZD/CAD', 5),
  ('NZD_CHF', 'NZD/CHF', 5),
  ('NZD_HKD', 'NZD/HKD', 5),
  ('NZD_JPY', 'NZD/JPY', 3),
  ('NZD_SGD', 'NZD/SGD', 5),
  ('NZD_USD', 'NZD/USD', 5),
  ('SGD_CHF', 'SGD/CHF', 5),
  ('SGD_JPY', 'SGD/JPY', 3),
  ('TRY_JPY', 'TRY/JPY', 3),
  ('USD_CAD', 'USD/CAD', 5),
  ('USD_CHF', 'USD/CHF', 5),
  ('USD_CNH', 'USD/CNH', 5),
  ('USD_CZK', 'USD/CZK', 5),
  ('USD_DKK', 'USD/DKK', 5),
  ('USD_HKD', 'USD/HKD', 5),
  ('USD_HUF', 'USD/HUF', 3),
  ('USD_JPY', 'USD/JPY', 3),
  ('USD_MXN', 'USD/MXN', 5),
  ('USD_NOK', 'USD/NOK', 5),
  ('USD_PLN', 'USD/PLN', 5),
  ('USD_SEK', 'USD/SEK', 5),
  ('USD_SGD', 'USD/SGD', 5),
  ('USD_THB', 'USD/THB', 3),
  ('USD_TRY', 'USD/TRY', 5),
  ('USD_ZAR', 'USD/ZAR', 5),
  ('ZAR_JPY', 'ZAR/JPY', 3)
ON CONFLICT (code) DO NOTHING;
