import { displayNameFor, pipSizeFor } from "@/lib/instruments/catalog";
import { calculateAtrValues, calculateEmaValues } from "@/lib/strategy/indicators";
import { resolveFrozenH1Exit, type FrozenH1ExitInput } from "@/lib/strategy/strategies/frozen-h1-pair";
import type { StrategyCandidate } from "@/lib/strategy/strategy";
import type { CadjpyStrategyFeatures, MarketRegime, StrategyCondition, StrategyEvaluationInput } from "@/lib/strategy/types";
import type { Candle } from "@/types/forex";

export const CADJPY_STRATEGY_ID = "cadjpy_strategy" as const;
export const CADJPY_STRATEGY_NAME = "CADJPY Bull Break Extreme V1" as const;
export const CADJPY_STRATEGY_VERSION = "V1" as const;
export const CADJPY_STRATEGY_CONFIG_VERSION = "cadjpy-v1-frozen" as const;
export const CADJPY_STRATEGY_SYMBOL = "CAD_JPY" as const;
export const CADJPY_STRATEGY_TIMEFRAME = "H1" as const;
export const CADJPY_STRATEGY_CONFIG = Object.freeze({ symbol: CADJPY_STRATEGY_SYMBOL, timeframe: CADJPY_STRATEGY_TIMEFRAME, originHourUtc: 12, direction: "LONG_ONLY", emaFastPeriod: 20, emaSlowPeriod: 50, atrPeriod: 14, consensus: ">= +3", previousHighBreak: true, bodyAtrMinimum: .5, upperClosePct: .25, stopAtr: 1, rewardR: 2, maxHoldBars: 3, executionEnabled: true, adaptiveParametersMutable: false });
export interface CadjpyPineEvaluation { originTime: string | null; signalMidClose: number | null; ema20: number | null; ema50: number | null; atr14: number | null; voteTrend: -1|0|1|null; votePrice: -1|0|1|null; voteSlope: -1|0|1|null; voteMomentum: -1|0|1|null; consensus: number | null; previousHigh: number | null; previousHighBreak: boolean; bullBody: boolean; bodyR: number | null; closeLocation: number | null; pineReferenceStop: number | null; pineReferenceTarget: number | null; strategySignalQualified: boolean; }
export interface CadjpyStrategyEvaluationOptions { timeframe?: string; hasActivePosition?: boolean; duplicateSignal?: boolean; }
const vote = (a:number,b:number): -1|0|1 => a>b?1:a<b?-1:0;
const finite = (v:number|null) => v !== null && Number.isFinite(v);
const exactH1 = (d:Date) => d.getUTCMinutes()===0 && d.getUTCSeconds()===0 && d.getUTCMilliseconds()===0;
const condition = (name:string,passed:boolean,reason:string,currentValue:string,required=true):StrategyCondition=>({name,passed,reason,currentValue,required});

/** Exact completed-H1 midpoint implementation; no session, news, spread, range, or ATR-clearance filters. */
export function evaluateCadjpyBullBreakExtremeV1(input: readonly Candle[]): CadjpyPineEvaluation {
 const candles=[...new Map(input.filter(c=>c.complete&&Number.isFinite(Date.parse(c.time))).map(c=>[c.time,c] as const)).values()].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)); const i=candles.length-1,c=candles.at(-1),p=candles.at(-2),b3=candles.at(-4),cl=candles.map(x=>x.close),e20s=calculateEmaValues(cl,20),e50s=calculateEmaValues(cl,50),atrs=calculateAtrValues(candles,14),ema20=e20s[i]??null,ema50=e50s[i]??null,ema20Back=e20s[i-3]??null,atr14=atrs[i]??null;
 const origin=Boolean(c&&exactH1(new Date(c.time))&&new Date(c.time).getUTCHours()===12),ready=Boolean(c&&p&&b3&&finite(ema20)&&finite(ema50)&&finite(ema20Back)&&finite(atr14)&&atr14!>0),voteTrend=ready?vote(ema20!,ema50!):null,votePrice=ready?vote(c!.close,ema20!):null,voteSlope=ready?vote(ema20!,ema20Back!):null,voteMomentum=ready?vote(c!.close,b3!.close):null,consensus=voteTrend===null||votePrice===null||voteSlope===null||voteMomentum===null?null:voteTrend+votePrice+voteSlope+voteMomentum;
 const range=c?c.high-c.low:null,body=c?Math.abs(c.close-c.open):null,bullBody=Boolean(c&&c.close>c.open),bodyR=body!==null&&finite(atr14)&&atr14!>0?body/atr14!:null,closeLocation=c&&range!==null&&range>0?(c.close-c.low)/range:null,previousHighBreak=Boolean(c&&p&&c.close>p.high),bodyExtreme=Boolean(bullBody&&bodyR!==null&&bodyR>=.5&&range!==null&&range>0&&closeLocation!==null&&closeLocation>=.75),strategySignalQualified=Boolean(ready&&origin&&consensus!==null&&consensus>=3&&previousHighBreak&&bodyExtreme),signalMidClose=strategySignalQualified&&c?c.close:null;
 return {originTime:c?.time??null,signalMidClose,ema20,ema50,atr14,voteTrend,votePrice,voteSlope,voteMomentum,consensus,previousHigh:p?.high??null,previousHighBreak,bullBody,bodyR,closeLocation,pineReferenceStop:signalMidClose!==null&&finite(atr14)?signalMidClose-atr14!:null,pineReferenceTarget:signalMidClose!==null&&finite(atr14)?signalMidClose+2*atr14!:null,strategySignalQualified};
}
function block(input:StrategyEvaluationInput,p:CadjpyPineEvaluation,o:CadjpyStrategyEvaluationOptions){if(!p.strategySignalQualified)return "NO_STRATEGY_SIGNAL";if(input.instrument!==CADJPY_STRATEGY_SYMBOL)return "WRONG_INSTRUMENT";if((o.timeframe??"H1")!=="H1")return "WRONG_TIMEFRAME";if(o.duplicateSignal)return "DUPLICATE_SIGNAL";if(o.hasActivePosition)return "CADJPY_V1_POSITION_ACTIVE";if(input.dataSource!=="oanda")return "OANDA_CONNECTION_UNAVAILABLE";if(!finite(input.ask))return "OANDA_PRICE_UNAVAILABLE";return null;}
function regime(p:CadjpyPineEvaluation,evaluatedAt:string):MarketRegime{return {regime:"mixed",trendDirection:p.ema20===null||p.ema50===null?"none":p.ema20>p.ema50?"up":p.ema20<p.ema50?"down":"none",trendStrength:0,volatility:"normal",atr:p.atr14,atrPips:p.atr14===null?null:p.atr14/pipSizeFor(CADJPY_STRATEGY_SYMBOL),momentumState:"steady",emaFast:p.ema20,emaMid:p.ema50,emaSlow:null,slopeAtrPerBar:null,rangeHigh:null,rangeLow:null,rangeWidthAtr:null,rangeAgeBars:null,lookbackBars:50,evaluatedAt};}
export function evaluateCadjpyStrategy(input:StrategyEvaluationInput,options:CadjpyStrategyEvaluationOptions={}):StrategyCandidate<typeof CADJPY_STRATEGY_ID>{const p=evaluateCadjpyBullBreakExtremeV1(input.candles1h),evaluatedAt=p.originTime?new Date(Date.parse(p.originTime)+3_600_000).toISOString():input.evaluatedAt??new Date(0).toISOString(),executionBlockReason=block(input,p,options),executionAllowed=p.strategySignalQualified&&executionBlockReason===null,entry=executionAllowed?input.ask:null,stop=entry!==null&&finite(p.atr14)?entry-p.atr14!:null,target=entry!==null&&finite(p.atr14)?entry+2*p.atr14!:null;
 const features:CadjpyStrategyFeatures={strategyId:CADJPY_STRATEGY_ID,strategyName:CADJPY_STRATEGY_NAME,strategyVersion:CADJPY_STRATEGY_VERSION,symbol:CADJPY_STRATEGY_SYMBOL,timeframe:"H1",signalKey:p.strategySignalQualified&&p.originTime?`CADJPY_1200_LONG:${p.originTime}`:null,originTime:p.originTime,signalMidClose:p.signalMidClose,actualExecutableEntry:entry,frozenAtr14:p.atr14,pineReferenceStop:p.pineReferenceStop,pineReferenceTarget:p.pineReferenceTarget,executableStop:stop,executableTarget:target,ema20:p.ema20,ema50:p.ema50,voteTrend:p.voteTrend,votePrice:p.votePrice,voteSlope:p.voteSlope,voteMomentum:p.voteMomentum,consensus:p.consensus,previousHigh:p.previousHigh,previousHighBreak:p.previousHighBreak,bullBody:p.bullBody,bodyR:p.bodyR,closeLocation:p.closeLocation,strategySignalQualified:p.strategySignalQualified,executionAllowed,executionBlockReason,maxHoldBars:3};
 const conditions=[condition("Pine completed 12:00 UTC origin",Boolean(p.originTime&&exactH1(new Date(p.originTime))&&new Date(p.originTime).getUTCHours()===12),"Only completed 12:00 UTC candle may signal.",p.originTime??"unavailable"),condition("Pine history",p.ema20!==null&&p.ema50!==null&&p.atr14!==null&&p.atr14>0&&p.voteSlope!==null,"EMA/ATR and lookbacks required.",p.atr14?.toString()??"unavailable"),condition("Pine consensus",p.consensus!==null&&p.consensus>=3,"Four votes total +3 or +4.",p.consensus?.toString()??"unavailable"),condition("Pine previous-high break",p.previousHighBreak,"Strict close > high[1], no ATR clearance.",p.previousHigh?.toString()??"unavailable"),condition("Pine bullish body",p.bullBody,"close > open.",p.bullBody?"bullish":"not bullish"),condition("Pine body strength",p.bodyR!==null&&p.bodyR>=.5,"Body >= .50 ATR.",p.bodyR?.toString()??"unavailable"),condition("Pine upper 25% close",p.closeLocation!==null&&p.closeLocation>=.75,"Close in upper 25%.",p.closeLocation?.toString()??"unavailable"),condition("Strategy signal qualified",p.strategySignalQualified,"Exact Pine result without broker policy.",p.strategySignalQualified?"qualified":"not qualified"),condition("Execution duplicate protection",!options.duplicateSignal,"Same origin submits once.",options.duplicateSignal?"duplicate":"clear",false),condition("Execution CADJPY position",!options.hasActivePosition,"Pyramiding scoped to CADJPY V1.",options.hasActivePosition?"active":"clear",false),condition("Execution OANDA connection",input.dataSource==="oanda","Connected OANDA data required.",input.dataSource,false),condition("Execution OANDA ASK",finite(input.ask),"Valid ASK required.",input.ask?.toString()??"unavailable",false)];
 return {family:CADJPY_STRATEGY_ID,version:CADJPY_STRATEGY_VERSION,configVersion:CADJPY_STRATEGY_CONFIG_VERSION,regime:regime(p,evaluatedAt),qualifyReason:p.strategySignalQualified?executionAllowed?"CADJPY Pine signal qualified and execution is allowed.":`CADJPY Pine signal qualified; execution blocked: ${executionBlockReason}.`:"CADJPY Pine signal did not qualify.",status:executionAllowed?"valid":"no_setup",instrument:input.instrument,pair:displayNameFor(input.instrument),direction:p.strategySignalQualified?"long":null,timeframe:"1h",entry,stop,target,riskReward:executionAllowed?2:null,positionSize:null,features:{trend15m:"mixed",trend1h:p.ema20!==null&&p.ema50!==null?p.ema20>p.ema50?"bullish":p.ema20<p.ema50?"bearish":"mixed":"mixed",trend4h:null,ema21:null,ema50:p.ema50,ema200:null,rsi14:null,atr14:p.atr14,atrPips:p.atr14===null?null:p.atr14/pipSizeFor(CADJPY_STRATEGY_SYMBOL),structureHighs:0,structureLows:0,evaluationMode:input.evaluationMode??"live",cadjpyStrategy:features},summary:p.strategySignalQualified?executionAllowed?"CADJPY Bull Break Extreme V1 LONG signal.":`CADJPY Bull Break Extreme V1 execution blocked: ${executionBlockReason}.`:"CADJPY Bull Break Extreme V1 WAIT.",passedConditions:conditions.filter(x=>x.passed),failedConditions:conditions.filter(x=>!x.passed),conditions,evaluatedAt,dataSource:input.dataSource};}
export const resolveCadjpyExit = (input: FrozenH1ExitInput) => resolveFrozenH1Exit(input);
