import { displayNameFor, pipSizeFor } from "@/lib/instruments/catalog";
import { calculateAtrValues, calculateEmaValues } from "@/lib/strategy/indicators";
import { resolveFrozenH1Exit, type FrozenH1ExitInput } from "@/lib/strategy/strategies/frozen-h1-pair";
import type { StrategyCandidate } from "@/lib/strategy/strategy";
import type { EurjpyStrategyFeatures, MarketRegime, StrategyCondition, StrategyEvaluationInput } from "@/lib/strategy/types";
import type { Candle } from "@/types/forex";

export const EURJPY_STRATEGY_ID = "eurjpy_strategy" as const;
export const EURJPY_STRATEGY_NAME = "EURJPY 01-05 Range Break V1" as const;
export const EURJPY_STRATEGY_VERSION = "V1" as const;
export const EURJPY_STRATEGY_CONFIG_VERSION = "eurjpy-v1-frozen" as const;
export const EURJPY_STRATEGY_SYMBOL = "EUR_JPY" as const;
export const EURJPY_STRATEGY_TIMEFRAME = "H1" as const;
export const EURJPY_STRATEGY_CONFIG = Object.freeze({ symbol: EURJPY_STRATEGY_SYMBOL, timeframe: EURJPY_STRATEGY_TIMEFRAME, originHourUtc: 6, direction: "LONG_ONLY", emaFastPeriod: 20, atrPeriod: 14, rangeHoursUtc: [1, 2, 3, 4, 5], ema20Slope: "positive_vs_3_bars_ago", previousHighBreak: true, preRangeHighBreak: true, stopAtr: 1, rewardR: 2, maxHoldBars: 3, executionEnabled: true, adaptiveParametersMutable: false });
export interface EurjpyPineEvaluation { originTime: string | null; signalMidClose: number | null; ema20: number | null; ema20Back: number | null; atr14: number | null; previousHigh: number | null; preRangeStart: string | null; preRangeEnd: string | null; preHigh: number | null; preLow: number | null; preRangeBarCount: number; rangeReady: boolean; emaSlopeUp: boolean; previousHighBreak: boolean; preRangeHighBreak: boolean; pineReferenceStop: number | null; pineReferenceTarget: number | null; strategySignalQualified: boolean; }
export interface EurjpyStrategyEvaluationOptions { timeframe?: string; hasActivePosition?: boolean; duplicateSignal?: boolean; }
const finite = (value: number | null) => value !== null && Number.isFinite(value);
const exactH1 = (value: Date) => value.getUTCMinutes() === 0 && value.getUTCSeconds() === 0 && value.getUTCMilliseconds() === 0;
const condition = (name: string, passed: boolean, reason: string, currentValue: string, required = true): StrategyCondition => ({ name, passed, reason, currentValue, required });
function completedUniqueH1(input: readonly Candle[]) { const byTime = new Map<string, Candle>(); for (const candle of input) if (candle.complete && Number.isFinite(Date.parse(candle.time)) && !byTime.has(candle.time)) byTime.set(candle.time, candle); return [...byTime.values()].sort((a, b) => Date.parse(a.time) - Date.parse(b.time)); }
const sameUtcDay = (left: Date, right: Date) => left.getUTCFullYear() === right.getUTCFullYear() && left.getUTCMonth() === right.getUTCMonth() && left.getUTCDate() === right.getUTCDate();

/** Literal Pine evaluator: completed 06:00 H1 candle, current UTC-day 01:00-05:00 range only. */
export function evaluateEurjpy01To05RangeBreakV1(input: readonly Candle[]): EurjpyPineEvaluation {
  const candles = completedUniqueH1(input), index = candles.length - 1, current = candles.at(-1), previous = candles.at(-2), threeBack = candles.at(-4);
  const closes = candles.map((candle) => candle.close), emaValues = calculateEmaValues(closes, 20), atrValues = calculateAtrValues(candles, 14);
  const ema20 = emaValues[index] ?? null, ema20Back = emaValues[index - 3] ?? null, atr14 = atrValues[index] ?? null, currentTime = current ? new Date(current.time) : null;
  const origin = Boolean(currentTime && exactH1(currentTime) && currentTime.getUTCHours() === 6);
  const rangeCandles = currentTime ? candles.filter((candle) => { const time = new Date(candle.time); return sameUtcDay(time, currentTime) && time.getUTCHours() >= 1 && time.getUTCHours() <= 5 && exactH1(time); }) : [];
  // Pine `ready` requires only `not na(preHigh)`: one or more of the current
  // UTC-day 01:00-05:00 bars. It has NO "exactly five range bars" gate, so this
  // matches the canonical Pine literally (empirically output-identical to a
  // 5-bar gate across 2023-2026, since partial-range days never break out).
  const rangeReady = rangeCandles.length >= 1;
  const preHigh = rangeReady ? Math.max(...rangeCandles.map((candle) => candle.high)) : null, preLow = rangeReady ? Math.min(...rangeCandles.map((candle) => candle.low)) : null;
  const ready = Boolean(current && previous && threeBack && finite(ema20) && finite(ema20Back) && finite(atr14) && atr14! > 0 && rangeReady && preHigh !== null);
  const emaSlopeUp = Boolean(ready && ema20! > ema20Back!), previousHighBreak = Boolean(ready && current!.close > previous!.high), preRangeHighBreak = Boolean(ready && current!.close > preHigh!);
  const strategySignalQualified = Boolean(origin && ready && emaSlopeUp && previousHighBreak && preRangeHighBreak), signalMidClose = strategySignalQualified && current ? current.close : null;
  return { originTime: current?.time ?? null, signalMidClose, ema20, ema20Back, atr14, previousHigh: previous?.high ?? null, preRangeStart: rangeCandles.find((candle) => new Date(candle.time).getUTCHours() === 1)?.time ?? null, preRangeEnd: rangeCandles.find((candle) => new Date(candle.time).getUTCHours() === 5)?.time ?? null, preHigh, preLow, preRangeBarCount: rangeCandles.length, rangeReady, emaSlopeUp, previousHighBreak, preRangeHighBreak, pineReferenceStop: signalMidClose !== null && finite(atr14) ? signalMidClose - atr14! : null, pineReferenceTarget: signalMidClose !== null && finite(atr14) ? signalMidClose + 2 * atr14! : null, strategySignalQualified };
}
function executionBlock(input: StrategyEvaluationInput, pine: EurjpyPineEvaluation, options: EurjpyStrategyEvaluationOptions) { if (!pine.strategySignalQualified) return "NO_STRATEGY_SIGNAL"; if (input.instrument !== EURJPY_STRATEGY_SYMBOL) return "WRONG_INSTRUMENT"; if ((options.timeframe ?? "H1") !== "H1") return "WRONG_TIMEFRAME"; if (options.duplicateSignal) return "DUPLICATE_SIGNAL"; if (options.hasActivePosition) return "EURJPY_V1_POSITION_ACTIVE"; if (input.dataSource !== "oanda") return "OANDA_CONNECTION_UNAVAILABLE"; if (!finite(input.ask)) return "OANDA_PRICE_UNAVAILABLE"; return null; }
function regime(pine: EurjpyPineEvaluation, evaluatedAt: string): MarketRegime { return { regime: "mixed", trendDirection: pine.ema20 === null || pine.ema20Back === null ? "none" : pine.ema20 > pine.ema20Back ? "up" : pine.ema20 < pine.ema20Back ? "down" : "none", trendStrength: 0, volatility: "normal", atr: pine.atr14, atrPips: pine.atr14 === null ? null : pine.atr14 / pipSizeFor(EURJPY_STRATEGY_SYMBOL), momentumState: "steady", emaFast: pine.ema20, emaMid: null, emaSlow: null, slopeAtrPerBar: null, rangeHigh: pine.preHigh, rangeLow: pine.preLow, rangeWidthAtr: pine.preHigh !== null && pine.preLow !== null && finite(pine.atr14) ? (pine.preHigh - pine.preLow) / pine.atr14! : null, rangeAgeBars: null, lookbackBars: 20, evaluatedAt }; }
export function evaluateEurjpyStrategy(input: StrategyEvaluationInput, options: EurjpyStrategyEvaluationOptions = {}): StrategyCandidate<typeof EURJPY_STRATEGY_ID> {
  const pine = evaluateEurjpy01To05RangeBreakV1(input.candles1h), evaluatedAt = pine.originTime ? new Date(Date.parse(pine.originTime) + 3_600_000).toISOString() : input.evaluatedAt ?? new Date(0).toISOString(), executionBlockReason = executionBlock(input, pine, options), executionAllowed = pine.strategySignalQualified && executionBlockReason === null, entry = executionAllowed ? input.ask : null, stop = entry !== null && finite(pine.atr14) ? entry - pine.atr14! : null, target = entry !== null && finite(pine.atr14) ? entry + 2 * pine.atr14! : null;
  const strategy: EurjpyStrategyFeatures = { strategyId: EURJPY_STRATEGY_ID, strategyName: EURJPY_STRATEGY_NAME, strategyVersion: EURJPY_STRATEGY_VERSION, symbol: EURJPY_STRATEGY_SYMBOL, timeframe: "H1", signalKey: pine.strategySignalQualified && pine.originTime ? `EURJPY_0600_LONG:${pine.originTime}` : null, originTime: pine.originTime, signalMidClose: pine.signalMidClose, actualExecutableEntry: entry, frozenAtr14: pine.atr14, pineReferenceStop: pine.pineReferenceStop, pineReferenceTarget: pine.pineReferenceTarget, executableStop: stop, executableTarget: target, ema20: pine.ema20, ema20Back: pine.ema20Back, previousHigh: pine.previousHigh, preRangeStart: pine.preRangeStart, preRangeEnd: pine.preRangeEnd, preHigh: pine.preHigh, preLow: pine.preLow, preRangeBarCount: pine.preRangeBarCount, rangeReady: pine.rangeReady, emaSlopeUp: pine.emaSlopeUp, previousHighBreak: pine.previousHighBreak, preRangeHighBreak: pine.preRangeHighBreak, strategySignalQualified: pine.strategySignalQualified, executionAllowed, executionBlockReason, maxHoldBars: 3 };
  const conditions = [condition("Pine completed 06:00 UTC origin", Boolean(pine.originTime && exactH1(new Date(pine.originTime)) && new Date(pine.originTime).getUTCHours() === 6), "Only the completed 06:00 UTC candle may signal.", pine.originTime ?? "unavailable"), condition("Pine history", pine.ema20 !== null && pine.ema20Back !== null && pine.atr14 !== null && pine.atr14 > 0, "EMA20, EMA20[3], and positive Wilder ATR14 are required.", pine.atr14?.toString() ?? "unavailable"), condition("Pine 01:00-05:00 range", pine.rangeReady, "One or more current UTC-day 01:00-05:00 H1 candles form the range (Pine: not na(preHigh)).", `${pine.preRangeBarCount} bar(s)`), condition("Pine EMA20 slope", pine.emaSlopeUp, "EMA20 must be greater than EMA20[3].", `${pine.ema20 ?? "?"} > ${pine.ema20Back ?? "?"}`), condition("Pine previous-high break", pine.previousHighBreak, "Strict close > high[1], without ATR clearance.", pine.previousHigh?.toString() ?? "unavailable"), condition("Pine pre-range-high break", pine.preRangeHighBreak, "Strict close > the 01:00-05:00 range high.", pine.preHigh?.toString() ?? "unavailable"), condition("Strategy signal qualified", pine.strategySignalQualified, "Exact Pine result, without execution policy.", pine.strategySignalQualified ? "qualified" : "not qualified"), condition("Execution duplicate protection", !options.duplicateSignal, "Same 06:00 origin submits once.", options.duplicateSignal ? "duplicate" : "clear", false), condition("Execution EURJPY position", !options.hasActivePosition, "Pyramiding is scoped to EURJPY V1.", options.hasActivePosition ? "active" : "clear", false), condition("Execution OANDA connection", input.dataSource === "oanda", "Connected OANDA data required.", input.dataSource, false), condition("Execution OANDA ASK", finite(input.ask), "Valid ASK required.", input.ask?.toString() ?? "unavailable", false)];
  return { family: EURJPY_STRATEGY_ID, version: EURJPY_STRATEGY_VERSION, configVersion: EURJPY_STRATEGY_CONFIG_VERSION, regime: regime(pine, evaluatedAt), qualifyReason: pine.strategySignalQualified ? executionAllowed ? "EURJPY Pine signal qualified and execution is allowed." : `EURJPY Pine signal qualified; execution blocked: ${executionBlockReason}.` : "EURJPY Pine signal did not qualify.", status: executionAllowed ? "valid" : "no_setup", instrument: input.instrument, pair: displayNameFor(input.instrument), direction: pine.strategySignalQualified ? "long" : null, timeframe: "1h", entry, stop, target, riskReward: executionAllowed ? 2 : null, positionSize: null, features: { trend15m: "mixed", trend1h: pine.ema20 === null || pine.ema20Back === null ? "mixed" : pine.ema20 > pine.ema20Back ? "bullish" : pine.ema20 < pine.ema20Back ? "bearish" : "mixed", trend4h: null, ema21: null, ema50: null, ema200: null, rsi14: null, atr14: pine.atr14, atrPips: pine.atr14 === null ? null : pine.atr14 / pipSizeFor(EURJPY_STRATEGY_SYMBOL), structureHighs: 0, structureLows: 0, evaluationMode: input.evaluationMode ?? "live", eurjpyStrategy: strategy }, summary: pine.strategySignalQualified ? executionAllowed ? "EURJPY 01-05 Range Break V1 LONG signal." : `EURJPY 01-05 Range Break V1 execution blocked: ${executionBlockReason}.` : "EURJPY 01-05 Range Break V1 WAIT.", passedConditions: conditions.filter((item) => item.passed), failedConditions: conditions.filter((item) => !item.passed), conditions, evaluatedAt, dataSource: input.dataSource };
}
export const resolveEurjpyExit = (input: FrozenH1ExitInput) => resolveFrozenH1Exit(input);
