import { displayNameFor, pipSizeFor } from "@/lib/instruments/catalog";
import { calculateAtrValues, calculateEmaValues } from "@/lib/strategy/indicators";
import { resolveFrozenH1Exit, type FrozenH1ExitInput } from "@/lib/strategy/strategies/frozen-h1-pair";
import type { StrategyCandidate } from "@/lib/strategy/strategy";
import type { MarketRegime, StrategyCondition, StrategyEvaluationInput, UsdcadStrategyFeatures } from "@/lib/strategy/types";
import type { Candle } from "@/types/forex";
export const USDCAD_STRATEGY_ID = "usdcad_strategy" as const;
export const USDCAD_STRATEGY_NAME = "USDCAD Structure EMA Reclaim V3 11:00 LONG Only" as const;
export const USDCAD_STRATEGY_VERSION = "V3" as const;
export const USDCAD_STRATEGY_CONFIG_VERSION = "usdcad-v3-frozen" as const;
export const USDCAD_STRATEGY_SYMBOL = "USD_CAD" as const;
export const USDCAD_STRATEGY_TIMEFRAME = "H1" as const;
export const USDCAD_STRATEGY_CONFIG = Object.freeze({ symbol: USDCAD_STRATEGY_SYMBOL, timeframe: USDCAD_STRATEGY_TIMEFRAME, originHourUtc: 11, direction: "LONG_ONLY", emaFastPeriod: 20, atrPeriod: 14, structure: "HH_HL", ema20Reclaim: true, stopAtr: 1, rewardR: 2, maxHoldBars: 3, executionEnabled: true, adaptiveParametersMutable: false });
export interface UsdcadPineEvaluation { originTime:string|null; signalMidClose:number|null; ema20:number|null; ema20Previous:number|null; atr14:number|null; currentHigh:number|null; previousHigh:number|null; currentLow:number|null; previousLow:number|null; closeCurrent:number|null; closePrevious:number|null; bullStructure:boolean; longReclaim:boolean; emaPenetrationR:number|null; emaPenLong:boolean; closeLocation:number|null; extremeLong:boolean; highConfidenceLong:boolean; signalTag:"USDCAD_1100_LONG_PEN_EXTREME"|"USDCAD_1100_LONG_BASE"|null; pineReferenceStop:number|null; pineReferenceTarget:number|null; strategySignalQualified:boolean; }
export interface UsdcadStrategyEvaluationOptions { timeframe?:string; hasActivePosition?:boolean; duplicateSignal?:boolean; }
const finite=(v:number|null)=>v!==null&&Number.isFinite(v); const exactH1=(d:Date)=>d.getUTCMinutes()===0&&d.getUTCSeconds()===0&&d.getUTCMilliseconds()===0; const c=(name:string,passed:boolean,reason:string,currentValue:string,required=true):StrategyCondition=>({name,passed,reason,currentValue,required});
function clean(input:readonly Candle[]){const by=new Map<string,Candle>();for(const x of input)if(x.complete&&Number.isFinite(Date.parse(x.time))&&!by.has(x.time))by.set(x.time,x);return [...by.values()].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));}
/** Literal V3 rawLongSignal. PEN and extreme are intentionally metadata only. */
export function evaluateUsdcadStructureEmaReclaimV3(input:readonly Candle[]):UsdcadPineEvaluation { const candles=clean(input),i=candles.length-1,current=candles.at(-1),previous=candles.at(-2),ema=calculateEmaValues(candles.map(x=>x.close),20),atrs=calculateAtrValues(candles,14),ema20=ema[i]??null,ema20Previous=ema[i-1]??null,atr14=atrs[i]??null,origin=Boolean(current&&exactH1(new Date(current.time))&&new Date(current.time).getUTCHours()===11),ready=Boolean(current&&previous&&finite(ema20)&&finite(ema20Previous)&&finite(atr14)&&atr14!>0),bullStructure=Boolean(ready&&current!.high>previous!.high&&current!.low>previous!.low),longReclaim=Boolean(ready&&previous!.close<=ema20Previous!&&current!.close>ema20!),strategySignalQualified=Boolean(origin&&ready&&bullStructure&&longReclaim),range=current?current.high-current.low:null,emaPenetrationR=finite(ema20)&&finite(atr14)&&atr14!>0&&current?(current.close-ema20!)/atr14!:null,emaPenLong=Boolean(emaPenetrationR!==null&&emaPenetrationR>=.25),closeLocation=current&&range!==null&&range>0?(current.close-current.low)/range:null,extremeLong=Boolean(closeLocation!==null&&closeLocation>=.75),highConfidenceLong=Boolean(strategySignalQualified&&emaPenLong&&extremeLong),signalMidClose=strategySignalQualified&&current?current.close:null;
return {originTime:current?.time??null,signalMidClose,ema20,ema20Previous,atr14,currentHigh:current?.high??null,previousHigh:previous?.high??null,currentLow:current?.low??null,previousLow:previous?.low??null,closeCurrent:current?.close??null,closePrevious:previous?.close??null,bullStructure,longReclaim,emaPenetrationR,emaPenLong,closeLocation,extremeLong,highConfidenceLong,signalTag:strategySignalQualified?(highConfidenceLong?"USDCAD_1100_LONG_PEN_EXTREME":"USDCAD_1100_LONG_BASE"):null,pineReferenceStop:signalMidClose!==null&&finite(atr14)?signalMidClose-atr14!:null,pineReferenceTarget:signalMidClose!==null&&finite(atr14)?signalMidClose+2*atr14!:null,strategySignalQualified}; }
function block(input:StrategyEvaluationInput,q:boolean,o:UsdcadStrategyEvaluationOptions){if(!q)return "NO_STRATEGY_SIGNAL";if(input.instrument!==USDCAD_STRATEGY_SYMBOL)return "WRONG_INSTRUMENT";if((o.timeframe??"H1")!=="H1")return "WRONG_TIMEFRAME";if(o.duplicateSignal)return "DUPLICATE_SIGNAL";if(o.hasActivePosition)return "USDCAD_V3_POSITION_ACTIVE";if(input.dataSource!=="oanda")return "OANDA_CONNECTION_UNAVAILABLE";if(!finite(input.ask))return "OANDA_PRICE_UNAVAILABLE";return null;}
function regime(p:UsdcadPineEvaluation,evaluatedAt:string):MarketRegime{return {regime:"mixed",trendDirection:p.ema20===null||p.ema20Previous===null?"none":p.ema20>p.ema20Previous?"up":p.ema20<p.ema20Previous?"down":"none",trendStrength:0,volatility:"normal",atr:p.atr14,atrPips:p.atr14===null?null:p.atr14/pipSizeFor(USDCAD_STRATEGY_SYMBOL),momentumState:"steady",emaFast:p.ema20,emaMid:null,emaSlow:null,slopeAtrPerBar:null,rangeHigh:null,rangeLow:null,rangeWidthAtr:null,rangeAgeBars:null,lookbackBars:20,evaluatedAt};}
export function evaluateUsdcadStrategy(input:StrategyEvaluationInput,options:UsdcadStrategyEvaluationOptions={}):StrategyCandidate<typeof USDCAD_STRATEGY_ID>{const p=evaluateUsdcadStructureEmaReclaimV3(input.candles1h),qualified=p.strategySignalQualified&&input.instrument===USDCAD_STRATEGY_SYMBOL&&(options.timeframe??"H1")==="H1",evaluatedAt=p.originTime?new Date(Date.parse(p.originTime)+3_600_000).toISOString():input.evaluatedAt??new Date(0).toISOString(),executionBlockReason=block(input,qualified,options),executionAllowed=qualified&&executionBlockReason===null,entry=executionAllowed?input.ask:null,stop=entry!==null&&finite(p.atr14)?entry-p.atr14!:null,target=entry!==null&&finite(p.atr14)?entry+2*p.atr14!:null;
const strategy:UsdcadStrategyFeatures={strategyId:USDCAD_STRATEGY_ID,strategyName:USDCAD_STRATEGY_NAME,strategyVersion:USDCAD_STRATEGY_VERSION,symbol:USDCAD_STRATEGY_SYMBOL,timeframe:"H1",signalKey:qualified&&p.originTime?`USDCAD_1100_LONG:${p.originTime}`:null,originTime:p.originTime,signalMidClose:p.signalMidClose,actualExecutableEntry:entry,frozenAtr14:p.atr14,pineReferenceStop:p.pineReferenceStop,pineReferenceTarget:p.pineReferenceTarget,executableStop:stop,executableTarget:target,currentHigh:p.currentHigh,previousHigh:p.previousHigh,currentLow:p.currentLow,previousLow:p.previousLow,ema20Current:p.ema20,ema20Previous:p.ema20Previous,closeCurrent:p.closeCurrent,closePrevious:p.closePrevious,bullStructure:p.bullStructure,longReclaim:p.longReclaim,emaPenetrationR:p.emaPenetrationR,emaPenLong:p.emaPenLong,closeLocation:p.closeLocation,extremeLong:p.extremeLong,highConfidenceLong:p.highConfidenceLong,signalTag:p.signalTag,strategySignalQualified:qualified,executionAllowed,executionBlockReason,maxHoldBars:3};
const conditions=[c("Pine USD_CAD instrument",input.instrument===USDCAD_STRATEGY_SYMBOL,"USD_CAD only.",input.instrument),c("Pine H1",(options.timeframe??"H1")==="H1","H1 only.",options.timeframe??"H1"),c("Pine completed 11:00 UTC origin",Boolean(p.originTime&&exactH1(new Date(p.originTime))&&new Date(p.originTime).getUTCHours()===11),"Only completed 11:00 may signal.",p.originTime??"unavailable"),c("Pine history",p.ema20!==null&&p.ema20Previous!==null&&p.atr14!==null&&p.atr14>0,"EMA20 current/previous, ATR and prior H/L/C required.",p.atr14?.toString()??"unavailable"),c("Pine HH + HL",p.bullStructure,"Strict high > high[1] and low > low[1].",`${p.currentHigh??"?"}/${p.currentLow??"?"}`),c("Pine EMA reclaim",p.longReclaim,"close[1] <= EMA20[1] and close > EMA20.",`${p.closePrevious??"?"}/${p.closeCurrent??"?"}`),c("Strategy signal qualified",qualified,"Exact rawLongSignal; PEN/extreme do not gate entry.",qualified?"qualified":"not qualified"),c("Execution duplicate protection",!options.duplicateSignal,"Same origin submits once.",options.duplicateSignal?"duplicate":"clear",false),c("Execution USDCAD position",!options.hasActivePosition,"Pyramiding scoped to USDCAD V3.",options.hasActivePosition?"active":"clear",false),c("Execution OANDA connection",input.dataSource==="oanda","Connected OANDA data required.",input.dataSource,false),c("Execution OANDA ASK",finite(input.ask),"Valid ASK required for a long.",input.ask?.toString()??"unavailable",false)];
return {family:USDCAD_STRATEGY_ID,version:USDCAD_STRATEGY_VERSION,configVersion:USDCAD_STRATEGY_CONFIG_VERSION,regime:regime(p,evaluatedAt),qualifyReason:qualified?executionAllowed?"USDCAD Pine signal qualified and execution is allowed.":`USDCAD Pine signal qualified; execution blocked: ${executionBlockReason}.`:"USDCAD Pine signal did not qualify.",status:executionAllowed?"valid":"no_setup",instrument:input.instrument,pair:displayNameFor(input.instrument),direction:qualified?"long":null,timeframe:"1h",entry,stop,target,riskReward:executionAllowed?2:null,positionSize:null,features:{trend15m:"mixed",trend1h:p.ema20===null||p.ema20Previous===null?"mixed":p.ema20>p.ema20Previous?"bullish":p.ema20<p.ema20Previous?"bearish":"mixed",trend4h:null,ema21:null,ema50:null,ema200:null,rsi14:null,atr14:p.atr14,atrPips:p.atr14===null?null:p.atr14/pipSizeFor(USDCAD_STRATEGY_SYMBOL),structureHighs:0,structureLows:0,evaluationMode:input.evaluationMode??"live",usdcadStrategy:strategy},summary:qualified?executionAllowed?"USDCAD Structure EMA Reclaim V3 LONG signal.":`USDCAD Structure EMA Reclaim V3 execution blocked: ${executionBlockReason}.`:"USDCAD Structure EMA Reclaim V3 WAIT.",passedConditions:conditions.filter(x=>x.passed),failedConditions:conditions.filter(x=>!x.passed),conditions,evaluatedAt,dataSource:input.dataSource};}
export const resolveUsdcadExit=(input:FrozenH1ExitInput)=>resolveFrozenH1Exit(input);
