import { displayNameFor, pipSizeFor } from "@/lib/instruments/catalog";
import { calculateAtrValues, calculateEmaValues } from "@/lib/strategy/indicators";
import { resolveFrozenH1Exit, type FrozenH1ExitInput } from "@/lib/strategy/strategies/frozen-h1-pair";
import type { StrategyCandidate } from "@/lib/strategy/strategy";
import type { MarketRegime, StrategyCondition, StrategyEvaluationInput, UsdchfStrategyFeatures } from "@/lib/strategy/types";
import type { Candle } from "@/types/forex";

export const USDCHF_STRATEGY_ID = "usdchf_strategy" as const;
export const USDCHF_STRATEGY_NAME = "USDCHF Bear Consensus Structure V1" as const;
export const USDCHF_STRATEGY_VERSION = "V1" as const;
export const USDCHF_STRATEGY_CONFIG_VERSION = "usdchf-v1-frozen" as const;
export const USDCHF_STRATEGY_SYMBOL = "USD_CHF" as const;
export const USDCHF_STRATEGY_TIMEFRAME = "H1" as const;
export const USDCHF_STRATEGY_CONFIG = Object.freeze({ symbol: USDCHF_STRATEGY_SYMBOL, timeframe: USDCHF_STRATEGY_TIMEFRAME, originHourUtc: 11, startTimeUtc: "2023-01-01T00:00:00.000Z", direction: "SHORT_ONLY", emaFastPeriod: 20, emaSlowPeriod: 50, atrPeriod: 14, consensus: "<= -3", structure: "LH_LL", stopAtr: 1, rewardR: 2, maxHoldBars: 3, executionEnabled: true, adaptiveParametersMutable: false });
export interface UsdchfPineEvaluation { originTime: string | null; signalMidClose: number | null; ema20: number | null; ema50: number | null; ema20Back: number | null; atr14: number | null; voteTrend: -1 | 0 | 1 | null; votePrice: -1 | 0 | 1 | null; voteSlope: -1 | 0 | 1 | null; voteMomentum: -1 | 0 | 1 | null; consensus: number | null; currentHigh: number | null; previousHigh: number | null; currentLow: number | null; previousLow: number | null; bearStructure: boolean; pineReferenceStop: number | null; pineReferenceTarget: number | null; strategySignalQualified: boolean; }
export interface UsdchfStrategyEvaluationOptions { timeframe?: string; hasActivePosition?: boolean; duplicateSignal?: boolean; }
const finite = (value: number | null) => value !== null && Number.isFinite(value);
const exactH1 = (value: Date) => value.getUTCMinutes() === 0 && value.getUTCSeconds() === 0 && value.getUTCMilliseconds() === 0;
const vote = (left: number, right: number): -1 | 0 | 1 => left > right ? 1 : left < right ? -1 : 0;
const condition = (name: string, passed: boolean, reason: string, currentValue: string, required = true): StrategyCondition => ({ name, passed, reason, currentValue, required });
const START_TIME_MS = Date.parse(USDCHF_STRATEGY_CONFIG.startTimeUtc);
function completedUniqueH1(input: readonly Candle[]) { const byTime = new Map<string, Candle>(); for (const candle of input) if (candle.complete && Number.isFinite(Date.parse(candle.time)) && !byTime.has(candle.time)) byTime.set(candle.time, candle); return [...byTime.values()].sort((a, b) => Date.parse(a.time) - Date.parse(b.time)); }

/** Exact Phase-3 baseline: four votes <= -3 plus only lower-high/lower-low structure. */
export function evaluateUsdchfBearConsensusStructureV1(input: readonly Candle[]): UsdchfPineEvaluation {
  const candles = completedUniqueH1(input), index = candles.length - 1, current = candles.at(-1), previous = candles.at(-2), threeBack = candles.at(-4), closes = candles.map((candle) => candle.close), ema20s = calculateEmaValues(closes, 20), ema50s = calculateEmaValues(closes, 50), atrs = calculateAtrValues(candles, 14);
  const ema20 = ema20s[index] ?? null, ema50 = ema50s[index] ?? null, ema20Back = ema20s[index - 3] ?? null, atr14 = atrs[index] ?? null, origin = Boolean(current && Date.parse(current.time) >= START_TIME_MS && exactH1(new Date(current.time)) && new Date(current.time).getUTCHours() === 11);
  const ready = Boolean(current && previous && threeBack && finite(ema20) && finite(ema50) && finite(ema20Back) && finite(atr14) && atr14! > 0);
  const voteTrend = ready ? vote(ema20!, ema50!) : null, votePrice = ready ? vote(current!.close, ema20!) : null, voteSlope = ready ? vote(ema20!, ema20Back!) : null, voteMomentum = ready ? vote(current!.close, threeBack!.close) : null;
  const consensus = voteTrend === null || votePrice === null || voteSlope === null || voteMomentum === null ? null : voteTrend + votePrice + voteSlope + voteMomentum;
  const bearStructure = Boolean(ready && current!.high < previous!.high && current!.low < previous!.low), strategySignalQualified = Boolean(origin && ready && consensus !== null && consensus <= -3 && bearStructure), signalMidClose = strategySignalQualified && current ? current.close : null;
  return { originTime: current?.time ?? null, signalMidClose, ema20, ema50, ema20Back, atr14, voteTrend, votePrice, voteSlope, voteMomentum, consensus, currentHigh: current?.high ?? null, previousHigh: previous?.high ?? null, currentLow: current?.low ?? null, previousLow: previous?.low ?? null, bearStructure, pineReferenceStop: signalMidClose !== null && finite(atr14) ? signalMidClose + atr14! : null, pineReferenceTarget: signalMidClose !== null && finite(atr14) ? signalMidClose - 2 * atr14! : null, strategySignalQualified };
}
function executionBlock(input: StrategyEvaluationInput, qualified: boolean, options: UsdchfStrategyEvaluationOptions) { if (!qualified) return "NO_STRATEGY_SIGNAL"; if (input.instrument !== USDCHF_STRATEGY_SYMBOL) return "WRONG_INSTRUMENT"; if ((options.timeframe ?? "H1") !== "H1") return "WRONG_TIMEFRAME"; if (options.duplicateSignal) return "DUPLICATE_SIGNAL"; if (options.hasActivePosition) return "USDCHF_V1_POSITION_ACTIVE"; if (input.dataSource !== "oanda") return "OANDA_CONNECTION_UNAVAILABLE"; if (!finite(input.bid)) return "OANDA_PRICE_UNAVAILABLE"; return null; }
function regime(pine: UsdchfPineEvaluation, evaluatedAt: string): MarketRegime { return { regime: "mixed", trendDirection: pine.ema20 === null || pine.ema50 === null ? "none" : pine.ema20 > pine.ema50 ? "up" : pine.ema20 < pine.ema50 ? "down" : "none", trendStrength: 0, volatility: "normal", atr: pine.atr14, atrPips: pine.atr14 === null ? null : pine.atr14 / pipSizeFor(USDCHF_STRATEGY_SYMBOL), momentumState: "steady", emaFast: pine.ema20, emaMid: pine.ema50, emaSlow: null, slopeAtrPerBar: null, rangeHigh: null, rangeLow: null, rangeWidthAtr: null, rangeAgeBars: null, lookbackBars: 50, evaluatedAt }; }
export function evaluateUsdchfStrategy(input: StrategyEvaluationInput, options: UsdchfStrategyEvaluationOptions = {}): StrategyCandidate<typeof USDCHF_STRATEGY_ID> {
  const pine = evaluateUsdchfBearConsensusStructureV1(input.candles1h), chartQualified = pine.strategySignalQualified && input.instrument === USDCHF_STRATEGY_SYMBOL && (options.timeframe ?? "H1") === "H1", evaluatedAt = pine.originTime ? new Date(Date.parse(pine.originTime) + 3_600_000).toISOString() : input.evaluatedAt ?? new Date(0).toISOString(), executionBlockReason = executionBlock(input, chartQualified, options), executionAllowed = chartQualified && executionBlockReason === null, entry = executionAllowed ? input.bid : null, stop = entry !== null && finite(pine.atr14) ? entry + pine.atr14! : null, target = entry !== null && finite(pine.atr14) ? entry - 2 * pine.atr14! : null;
  const strategy: UsdchfStrategyFeatures = { strategyId: USDCHF_STRATEGY_ID, strategyName: USDCHF_STRATEGY_NAME, strategyVersion: USDCHF_STRATEGY_VERSION, symbol: USDCHF_STRATEGY_SYMBOL, timeframe: "H1", signalKey: chartQualified && pine.originTime ? `USDCHF_1100_SHORT:${pine.originTime}` : null, originTime: pine.originTime, signalMidClose: pine.signalMidClose, actualExecutableEntry: entry, frozenAtr14: pine.atr14, pineReferenceStop: pine.pineReferenceStop, pineReferenceTarget: pine.pineReferenceTarget, executableStop: stop, executableTarget: target, ema20: pine.ema20, ema50: pine.ema50, ema20Back: pine.ema20Back, voteTrend: pine.voteTrend, votePrice: pine.votePrice, voteSlope: pine.voteSlope, voteMomentum: pine.voteMomentum, consensus: pine.consensus, currentHigh: pine.currentHigh, previousHigh: pine.previousHigh, currentLow: pine.currentLow, previousLow: pine.previousLow, bearStructure: pine.bearStructure, strategySignalQualified: chartQualified, executionAllowed, executionBlockReason, maxHoldBars: 3 };
  const conditions = [condition("Pine USDCHF instrument", input.instrument === USDCHF_STRATEGY_SYMBOL, "USDCHF only.", input.instrument), condition("Pine H1", (options.timeframe ?? "H1") === "H1", "H1 only.", options.timeframe ?? "H1"), condition("Pine completed 11:00 UTC origin", Boolean(pine.originTime && Date.parse(pine.originTime) >= START_TIME_MS && exactH1(new Date(pine.originTime)) && new Date(pine.originTime).getUTCHours() === 11), "Only the completed 11:00 candle after the frozen start time may signal.", pine.originTime ?? "unavailable"), condition("Pine history", pine.ema20 !== null && pine.ema50 !== null && pine.ema20Back !== null && pine.atr14 !== null && pine.atr14 > 0, "EMA20/50, EMA20[3], close[3], high/low[1], and ATR14 required.", pine.atr14?.toString() ?? "unavailable"), condition("Pine consensus", pine.consensus !== null && pine.consensus <= -3, "Four votes must total -3 or -4.", pine.consensus?.toString() ?? "unavailable"), condition("Pine bear structure", pine.bearStructure, "Strict high < high[1] AND low < low[1].", `${pine.currentHigh ?? "?"}/${pine.currentLow ?? "?"}`), condition("Strategy signal qualified", chartQualified, "Exact Pine result without execution policy.", chartQualified ? "qualified" : "not qualified"), condition("Execution duplicate protection", !options.duplicateSignal, "Same 11:00 origin submits once.", options.duplicateSignal ? "duplicate" : "clear", false), condition("Execution USDCHF position", !options.hasActivePosition, "Pyramiding is scoped to USDCHF V1.", options.hasActivePosition ? "active" : "clear", false), condition("Execution OANDA connection", input.dataSource === "oanda", "Connected OANDA data required.", input.dataSource, false), condition("Execution OANDA BID", finite(input.bid), "Valid BID required for a short.", input.bid?.toString() ?? "unavailable", false)];
  return { family: USDCHF_STRATEGY_ID, version: USDCHF_STRATEGY_VERSION, configVersion: USDCHF_STRATEGY_CONFIG_VERSION, regime: regime(pine, evaluatedAt), qualifyReason: chartQualified ? executionAllowed ? "USDCHF Pine signal qualified and execution is allowed." : `USDCHF Pine signal qualified; execution blocked: ${executionBlockReason}.` : "USDCHF Pine signal did not qualify.", status: executionAllowed ? "valid" : "no_setup", instrument: input.instrument, pair: displayNameFor(input.instrument), direction: chartQualified ? "short" : null, timeframe: "1h", entry, stop, target, riskReward: executionAllowed ? 2 : null, positionSize: null, features: { trend15m: "mixed", trend1h: pine.ema20 === null || pine.ema50 === null ? "mixed" : pine.ema20 > pine.ema50 ? "bullish" : pine.ema20 < pine.ema50 ? "bearish" : "mixed", trend4h: null, ema21: null, ema50: pine.ema50, ema200: null, rsi14: null, atr14: pine.atr14, atrPips: pine.atr14 === null ? null : pine.atr14 / pipSizeFor(USDCHF_STRATEGY_SYMBOL), structureHighs: 0, structureLows: 0, evaluationMode: input.evaluationMode ?? "live", usdchfStrategy: strategy }, summary: chartQualified ? executionAllowed ? "USDCHF Bear Consensus Structure V1 SHORT signal." : `USDCHF Bear Consensus Structure V1 execution blocked: ${executionBlockReason}.` : "USDCHF Bear Consensus Structure V1 WAIT.", passedConditions: conditions.filter((item) => item.passed), failedConditions: conditions.filter((item) => !item.passed), conditions, evaluatedAt, dataSource: input.dataSource };
}
export const resolveUsdchfExit = (input: FrozenH1ExitInput) => resolveFrozenH1Exit(input);
