import assert from 'node:assert/strict';
import {measureBrokerExecution,comparableExecutedR,requiresBrokerCloseConfirmation} from '../../src/execution-measurement.js';
import {buildEvidenceV2} from '../../src/adaptive-evidence-v2.js';
import {confirmEntryV2,replayEntryPlan,type EntryOpportunity,type ExecutableMinute} from '../../src/four-family-entry-v2.js';
const input={instrument:'EUR_USD' as const,direction:'long' as const,signalEntry:1.1,stop:1.099,nominalRiskAmount:1000,requestedUnits:1000000,inverted:false};
const state={state:'CLOSED',closed:true,entryPrice:1.1,averageClosePrice:1.102,initialUnits:100000,realizedPL:200,closeTime:'2026-09-04T12:00:00Z',openTime:'2026-09-04T10:00:00Z',financing:0};
const measured=measureBrokerExecution(input,state)!;
assert.ok(Math.abs(measured.priceResultR-2)<1e-9);
assert.equal(measured.nominalBudgetR,.2);
const smaller=measureBrokerExecution(input,{...state,initialUnits:10000,realizedPL:20})!;
assert.equal(measured.priceResultR,smaller.priceResultR,'broker size cannot change strategy R');
assert.ok(Math.abs(measured.cashRiskR!-smaller.cashRiskR!)<1e-9);
assert.equal(measureBrokerExecution(input,{...state,entryPrice:null}),null);
assert.equal(measureBrokerExecution(input,{...state,initialUnits:-100000}),null);
assert.equal(measureBrokerExecution(input,{...state,closed:false}),null);
for(const status of ['pending','sending','unknown'])assert.equal(requiresBrokerCloseConfirmation({status,broker_trade_id:null}),true,'indeterminate orders stay open');
assert.equal(requiresBrokerCloseConfirmation({status:'submitted',broker_trade_id:'123'}),true,'confirmed order needs actual close facts');
for(const status of ['submitted','rejected','failed','disabled'])assert.equal(requiresBrokerCloseConfirmation({status,broker_trade_id:null}),false,'confirmed absence of a broker trade permits model closure');
assert.equal(requiresBrokerCloseConfirmation(undefined),false);
assert.equal(comparableExecutedR({resultBasis:'model',modelR:2,orderStatus:'submitted',measurement:null,policy:'follow-v1',asOf:'2026-09-05'}),null,'submitted model close cannot masquerade as broker evidence');
assert.equal(comparableExecutedR({resultBasis:'broker',modelR:.2,orderStatus:'submitted',measurement:measured,policy:'follow-v1',asOf:'2026-09-03'}),null,'future close excluded');
const observation={family:'momentum',configVersion:'momentum-cfg-v1',policy:'momentum-inversion-v1' as const,instrument:'EUR_USD',session:'London',regime:'mixed',direction:'long',resultR:1,resolvedAt:'2026-09-04'};
const evidence=buildEvidenceV2([observation,{...observation,policy:'follow-v1',resultR:-100},{...observation,configVersion:'old'},{...observation,resolvedAt:'2026-09-06'}],new Date('2026-09-05'));
assert.equal(evidence.totalResolved,1,'opposite policies, configs, and future results stay out');
const base:EntryOpportunity={family:'breakout',time:900000,direction:'long',rawDirection:'long',entry:11,stop:8,target:17,signal:{time:900000,open:10,high:12,low:10,close:11},rangeHigh:10,rangeLow:8,breakoutLevel:10};
const retest={time:1800000,open:11,high:11,low:9.9,close:10.5};
const reclaim={time:2700000,open:10.5,high:11.2,low:10.2,close:11};
assert.equal(confirmEntryV2(base,[retest]).status,'wait','same-candle retest is not a subsequent reclaim');
assert.equal(confirmEntryV2(base,[retest,reclaim]).status,'confirmed');
assert.equal(confirmEntryV2(base,[reclaim]).status,'data_incomplete');
assert.equal(confirmEntryV2({...base,family:'momentum'},[{...retest,close:9.8}]).status,'confirmed');
assert.equal(confirmEntryV2({...base,family:'momentum',signal:{...base.signal,close:9.8}},[retest]).status,'wait');
assert.equal(confirmEntryV2({...base,family:'ema'},[{...retest,low:7}]).status,'invalidated');
const minute:ExecutableMinute={time:0,bo:10,bh:12.2,bl:8.8,bc:10,ao:10.1,ah:12.3,al:8.9,ac:10.1};
const plan={time:0,direction:'long' as const,entry:10,stop:9,target:12,forcedAt:60000,pip:.01,slippagePips:0};
assert.equal(replayEntryPlan(plan,[minute]).r,-1,'ambiguous intraminute path stops conservatively');
assert.equal(replayEntryPlan(plan,[{...minute,bo:8.5}]).r,-1.5,'gap stop uses adverse open');
assert.equal(replayEntryPlan(plan,[{...minute,time:60000}]).status,'data_incomplete','missing entry minute never filled forward');
assert.equal(replayEntryPlan(plan,[{...minute,bo:12.1}]).r,2,'known target at open precedes intraminute low');
assert.equal(replayEntryPlan({...plan,time:30000,entryTiming:'within_minute'},[{...minute,bo:8.5}]).status,'data_incomplete','pre-fill open and extrema cannot become a fictitious gap loss');
assert.equal(replayEntryPlan({...plan,entryTiming:'within_minute'},[minute]).status,'data_incomplete','unknown model fill timing also requires an unresolved first-bar touch');
assert.equal(replayEntryPlan({...plan,time:30000},[{...minute,bh:10.5,bl:9.5,bc:10.2}]).reason,'SESSION_CLOSE','safe partial entry bar can proceed to a known later close');
const first=replayEntryPlan(plan,[minute]);
assert.deepEqual(replayEntryPlan(plan,[minute,{...minute,time:60000,bc:99}]),first,'post-exit prices cannot change results');
assert.ok(replayEntryPlan({...plan,slippagePips:.5},[minute]).r!<first.r!,'adverse slippage cannot improve the tested stop outcome');
console.log('Execution normalization, policy isolation, causal entry, gaps and conservative replay checks passed.');
