/** M1 compression-to-expansion direction study. Research only; no production writes. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";
import { getResearchCandles } from "../../frontend/src/lib/oanda/client.js";
import type { MajorInstrument } from "../../frontend/src/types/forex.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
for (const file of [".env", ".env.local"]) loadDotenv({ path: path.join(root, file), override: false });
const OUT = path.join(root, "research-v2", "compression-expansion-binary-v1"), REPORT = path.join(OUT, "FINAL_REPORT.txt");
const INSTRUMENTS: MajorInstrument[] = ["EUR_USD", "GBP_USD", "USD_JPY", "AUD_USD", "NZD_USD", "USD_CAD", "USD_CHF", "EUR_GBP", "EUR_JPY", "GBP_JPY", "AUD_JPY", "EUR_AUD"];
const BARS = 20_000, PAGE = 5_000, HORIZON = 10, COMPRESSION_BARS = 12, PRIOR_BARS = 24, ATR_PERIOD = 14, MAX_RATIO = .65, MAX_WIDTH_ATR = 2, MIN_BODY_ATR = .25, DEDUP_MS = 15 * 60_000, BE80 = 1 / 1.8;
type Candle = { time: string; open: number; high: number; low: number; close: number }; type Dir = "up" | "down";
type Event = { instrument: string; at: string; ms: number; direction: Dir; outcome: "won" | "lost" | "tie"; compressionRatio: number; widthAtr: number };
type Score = { n: number; wins: number; losses: number; ties: number; rate: number | null; low: number | null; high: number | null };

async function fetchM1(instrument: MajorInstrument): Promise<Candle[]> { const rows = new Map<string, Candle>(); let cursor: string | undefined; for (let page = 0; page < Math.ceil(BARS / PAGE) + 1; page++) { const raw = await getResearchCandles(instrument, "M1", PAGE, cursor ? { to: cursor } : {}); const batch = raw.filter((c) => c.complete).map((c) => ({ time: c.time, open: c.mid.open, high: c.mid.high, low: c.mid.low, close: c.mid.close })); if (!batch.length) break; for (const c of batch) rows.set(c.time, c); cursor = batch.reduce((a, c) => c.time < a ? c.time : a, batch[0]!.time); if (rows.size >= BARS) break; await new Promise((done) => setTimeout(done, 120)); } return [...rows.values()].sort((a, b) => a.time.localeCompare(b.time)).slice(-BARS); }
function atr(c: Candle[]) { const out = new Float64Array(c.length).fill(NaN); let value = 0; for (let i = 1; i < c.length; i++) { const tr = Math.max(c[i]!.high - c[i]!.low, Math.abs(c[i]!.high - c[i - 1]!.close), Math.abs(c[i]!.low - c[i - 1]!.close)); value = i === 1 ? tr : (value * (ATR_PERIOD - 1) + tr) / ATR_PERIOD; if (i >= ATR_PERIOD) out[i] = value; } return out; }
function range(c: Candle[], from: number, to: number) { const rows = c.slice(from, to); return { high: Math.max(...rows.map((x) => x.high)), low: Math.min(...rows.map((x) => x.low)) }; }
function contiguous(c: Candle[], from: number, to: number) { for (let i = from + 1; i <= to; i++) if (Date.parse(c[i]!.time) - Date.parse(c[i - 1]!.time) !== 60_000) return false; return true; }
function ci(w: number, n: number) { if (!n) return { low: null, high: null }; const z = 1.96, p = w / n, d = 1 + z * z / n, middle = p + z * z / (2 * n), spread = z * Math.sqrt((p * (1 - p) + z * z / (4 * n)) / n); return { low: (middle - spread) / d, high: (middle + spread) / d }; }
function score(events: Event[], inverse = false): Score { const wins = events.filter((e) => e.outcome === (inverse ? "lost" : "won")).length, losses = events.filter((e) => e.outcome === (inverse ? "won" : "lost")).length, ties = events.length - wins - losses, n = wins + losses, interval = ci(wins, n); return { n, wins, losses, ties, rate: n ? wins / n : null, low: interval.low, high: interval.high }; }
function show(s: Score) { const p = (n: number | null) => n == null ? "n/a" : `${(n * 100).toFixed(2)}%`; return `n=${s.n} W/L/T=${s.wins}/${s.losses}/${s.ties} WR=${p(s.rate)} CI95=[${p(s.low)},${p(s.high)}]`; }
function collect(instrument: string, candles: Candle[]): Event[] { const values = atr(candles), events: Event[] = []; let last = -Infinity; for (let i = PRIOR_BARS + COMPRESSION_BARS; i < candles.length - HORIZON; i++) { if (!contiguous(candles, i - PRIOR_BARS - COMPRESSION_BARS, i + HORIZON)) continue; const a = values[i - 1]; if (!(a > 0)) continue; const compressed = range(candles, i - COMPRESSION_BARS, i), prior = range(candles, i - COMPRESSION_BARS - PRIOR_BARS, i - COMPRESSION_BARS), width = compressed.high - compressed.low, priorWidth = prior.high - prior.low, ratio = width / priorWidth; if (!(priorWidth > 0) || ratio > MAX_RATIO || width / a > MAX_WIDTH_ATR) continue; const bar = candles[i]!, body = Math.abs(bar.close - bar.open); let direction: Dir | null = null; if (bar.close > compressed.high && bar.close > bar.open && body >= MIN_BODY_ATR * a) direction = "up"; if (bar.close < compressed.low && bar.close < bar.open && body >= MIN_BODY_ATR * a) direction = "down"; if (!direction) continue; const ms = Date.parse(bar.time); if (ms - last < DEDUP_MS) continue; const exit = candles[i + HORIZON]!.close, outcome = Math.abs(exit - bar.close) < 1e-10 ? "tie" : (direction === "up" ? exit > bar.close : exit < bar.close) ? "won" : "lost"; events.push({ instrument, at: bar.time, ms, direction, outcome, compressionRatio: ratio, widthAtr: width / a }); last = ms; } return events; }

fs.mkdirSync(OUT, { recursive: true }); const all: Event[] = [];
for (const instrument of INSTRUMENTS) { const candles = await fetchM1(instrument), events = collect(instrument, candles); all.push(...events); console.log(`${instrument}: ${candles.length} M1, ${events.length} compression-expansion events`); }
all.sort((a, b) => a.ms - b.ms); if (!all.length) throw new Error("No events found"); const first = all[0]!.ms, last = all.at(-1)!.ms, t60 = first + (last - first) * .6, t80 = first + (last - first) * .8; const train = all.filter((e) => e.ms <= t60), dev = all.filter((e) => e.ms > t60 && e.ms <= t80), holdout = all.filter((e) => e.ms > t80); const normal = score(dev), inverse = score(dev, true), qualifies = (s: Score) => s.n >= 100 && (s.rate ?? 0) > BE80 && (s.low ?? 0) > .5, selected = qualifies(normal) ? "continuation" : qualifies(inverse) ? "inverse" : null;
const lines = ["GOLDENXPERIENCE — M1 COMPRESSION-EXPANSION DIRECTION STUDY", "Research only. No production strategy, trade, or prediction record changed.", "", `FROZEN RULE: preceding 12 completed M1 candles have width <=${(MAX_RATIO * 100).toFixed(0)}% of the prior 24-minute width and <=${MAX_WIDTH_ATR} ATR14; next completed candle closes outside the range with body >=${MIN_BODY_ATR} ATR14; entry=that close; target=mid close 10 minutes later.`, `Data: ${all.length} events across 12 pairs, ${new Date(first).toISOString()} → ${new Date(last).toISOString()}.`, `Chronological: TRAIN through ${new Date(t60).toISOString()} | DEV through ${new Date(t80).toISOString()} | HOLDOUT after.`, "", `TRAIN continuation: ${show(score(train))}`, `TRAIN exact inverse: ${show(score(train, true))}`, `DEV continuation: ${show(normal)}`, `DEV exact inverse: ${show(inverse)}`, `Gate: n>=100, WR>${(BE80 * 100).toFixed(2)}%, Wilson lower >50%. Selected for holdout: ${selected ?? "NONE"}.`];
if (selected) { const h = score(holdout, selected === "inverse"); lines.push(`HOLDOUT ${selected}: ${show(h)}`, `Holdout verdict: ${h.n >= 100 && (h.rate ?? 0) > BE80 && (h.low ?? 0) > .5 ? "CANDIDATE" : "FAIL"}`); } else lines.push("HOLDOUT NOT READ — neither direction passed the frozen DEV gate.");
lines.push("", "By direction (diagnostic):", ...(["up", "down"] as Dir[]).flatMap((d) => [`${d} DEV continuation: ${show(score(dev.filter((e) => e.direction === d)))}`, `${d} DEV inverse: ${show(score(dev.filter((e) => e.direction === d), true))}`])); fs.writeFileSync(REPORT, lines.join("\n") + "\n"); console.log(lines.join("\n")); console.log(`Wrote ${REPORT}`);
