/** Read-only EUR/USD V3 screen for unusually large, direction-neutral moves. */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";
import { evaluateEurUsdMoveGateV1 } from "../src/eur-usd-move-gate-v1.js";
import type { Candle } from "../../frontend/src/types/forex.js";
type Bar = { closeTime: string; open: number; high: number; low: number; close: number; bidClose: number; bidHigh: number; bidLow: number; askClose: number; askHigh: number; askLow: number; complete: true };
type Observation = { time: string; strength: number; longReach: number; shortReach: number };
type Period = { start: string; end: string };
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."); for (const name of [".env", ".env.local"]) loadDotenv({ path: path.join(root, name), override: false }); if (process.env.DATABASE_PUBLIC_URL) process.env.DATABASE_URL = process.env.DATABASE_PUBLIC_URL;
const { query } = await import("../src/database.js"); const output = path.join(root, "research-v2", "eur-usd-move-gate-v3-large-moves"); if (!existsSync(output)) mkdirSync(output, { recursive: true });
const TRAIN: Period = { start: "2021-06-03T00:00:00.000Z", end: "2023-01-01T00:00:00.000Z" }; const VALIDATION: Period = { start: "2023-01-01T00:00:00.000Z", end: "2024-01-01T00:00:00.000Z" }; const HOLDOUT: Period = { start: "2024-01-01T00:00:00.000Z", end: "2025-08-01T00:00:00.000Z" };
const THRESHOLDS = [1, 1.25, 1.5] as const; const TARGET_MULTIPLES = [2.5, 3] as const; const HOURS = new Set([0, 4, 8, 12, 16, 20]); const BAR_MS = 900_000; const HORIZON_BARS = 16;
function lower99(h: number, n: number) { if (!n) return 0; const z = 2.576, p = h / n; return (p + z * z / (2 * n) - z * Math.sqrt((p * (1 - p) + z * z / (4 * n)) / n)) / (1 + z * z / n); }
function seeded(time: string, seed: number) { let h = 2166136261 ^ seed; for (const c of `EUR_USD|${time}`) h = Math.imul(h ^ c.charCodeAt(0), 16777619); h ^= h >>> 16; h = Math.imul(h, 0x85ebca6b); h ^= h >>> 13; h = Math.imul(h, 0xc2b2ae35); h ^= h >>> 16; return h >>> 0; }
function hit(row: Observation, multiplier: number) { return row.longReach >= multiplier || row.shortReach >= multiplier; }
function score(rows: Observation[], multiplier: number) { const hits = rows.filter((row) => hit(row, multiplier)).length; return { n: rows.length, hits, hitRate: rows.length ? hits / rows.length : 0, lower99: lower99(hits, rows.length) }; }
function random(all: Observation[], count: number, multiplier: number) { const rates = Array.from({ length: 100 }, (_, seed) => score([...all].sort((a, b) => seeded(a.time, seed + 1) - seeded(b.time, seed + 1)).slice(0, count), multiplier).hitRate).sort((a, b) => a - b); return { count: 100, meanHitRate: rates.reduce((s, v) => s + v, 0) / rates.length, p95HitRate: rates[94] ?? 0 }; }
function candles(bars: Bar[]): Candle[] { return bars.map((bar) => ({ time: bar.closeTime, open: bar.open, high: bar.high, low: bar.low, close: bar.close, volume: 0, complete: true })); }
function observations(bars: Bar[], period: Period) { const rows: Observation[] = []; for (let i = 199; i < bars.length - HORIZON_BARS; i += 1) { const bar = bars[i]!, ms = Date.parse(bar.closeTime), d = new Date(ms); if (bar.closeTime < period.start || bar.closeTime >= period.end || d.getUTCMinutes() !== 0 || !HOURS.has(d.getUTCHours())) continue; const future = bars.slice(i + 1, i + 1 + HORIZON_BARS); if (future.length !== HORIZON_BARS || Date.parse(future.at(-1)!.closeTime) - ms !== HORIZON_BARS * BAR_MS) continue; const decision = evaluateEurUsdMoveGateV1({ instrument: "EUR_USD", candles: candles(bars.slice(i - 199, i + 1)), bid: bar.bidClose, ask: bar.askClose }); const atr = decision.atr, strength = decision.movementStrength; if (atr === null || strength === null) continue; const longReach = Math.max(0, ...future.map((next) => (next.bidHigh - bar.askClose) / atr)); const shortReach = Math.max(0, ...future.map((next) => (bar.bidClose - next.askLow) / atr)); rows.push({ time: bar.closeTime, strength, longReach, shortReach }); } return rows; }
function lane(all: Observation[], threshold: number, multiplier: number) { const selected = all.filter((row) => row.strength >= threshold); const result = score(selected, multiplier); const controls = random(all, selected.length, multiplier); return { threshold, targetAtr: multiplier, ...result, liftOverRandom: result.hitRate - controls.meanHitRate, randomControls: controls }; }
function passesTrain(row: ReturnType<typeof lane>) { return row.n >= 250 && row.liftOverRandom >= 0.1 && row.lower99 > row.randomControls.p95HitRate; }
function passesValidation(row: ReturnType<typeof lane>) { return row.n >= 125 && row.liftOverRandom >= 0.1 && row.lower99 > row.randomControls.p95HitRate; }
const records = await query<{ close_time: string; bid_open: number; bid_high: number; bid_low: number; bid_close: number; ask_open: number; ask_high: number; ask_low: number; ask_close: number }>(`SELECT close_time::text,bid_open::float,bid_high::float,bid_low::float,bid_close::float,ask_open::float,ask_high::float,ask_low::float,ask_close::float FROM market_candle_quotes WHERE instrument='EUR_USD' AND timeframe='M15' AND source='oanda' AND close_time >= $1 AND close_time < $2 ORDER BY close_time`, [TRAIN.start, HOLDOUT.end]);
const bars: Bar[] = records.rows.map((r) => ({ closeTime: new Date(r.close_time).toISOString(), open: (r.bid_open + r.ask_open) / 2, high: (r.bid_high + r.ask_high) / 2, low: (r.bid_low + r.ask_low) / 2, close: (r.bid_close + r.ask_close) / 2, bidClose: r.bid_close, bidHigh: r.bid_high, bidLow: r.bid_low, askClose: r.ask_close, askHigh: r.ask_high, askLow: r.ask_low, complete: true }));
const trainRows = observations(bars, TRAIN), validationRows = observations(bars, VALIDATION); const lanes = TARGET_MULTIPLES.flatMap((targetAtr) => THRESHOLDS.map((threshold) => lane(trainRows, threshold, targetAtr))); const nominated = lanes.filter(passesTrain).sort((a, b) => b.liftOverRandom - a.liftOverRandom || b.lower99 - a.lower99 || b.threshold - a.threshold)[0] ?? null; const validation = nominated ? lane(validationRows, nominated.threshold, nominated.targetAtr) : null; const qualified = nominated !== null && validation !== null && passesValidation(validation) && nominated.n + validation.n >= 500;
const report: Record<string, unknown> = { generatedAt: new Date().toISOString(), scope: { instrument: "EUR_USD", source: "stored OANDA M15 bid/ask market quotes only", decisions: "non-overlapping completed M15 closes at six fixed UTC four-hour boundaries", labels: "either executable side reaches +2.5 ATR or +3.0 ATR within four hours, without a stop or direction", features: "frozen V1 movement-strength score; only predeclared score and target thresholds", excludes: "trade rows, shadow writes, paper execution, direction selection, and post-result parameter changes" }, splits: { train: TRAIN, validation: VALIDATION, sealedHoldout: HOLDOUT }, train: lanes, nominationRule: "n >=250; lift >=10 points over random mean; 99% lower bound above random p95; largest lift wins", nominated, validation, validationRule: "n >=125; lift >=10 points; 99% lower bound above random p95; combined train+validation n >=500", qualifiedForSealedHoldout: qualified };
if (qualified && nominated) { report.sealedHoldout = lane(observations(bars, HOLDOUT), nominated.threshold, nominated.targetAtr); report.verdict = "V3_QUALIFIED_HOLDOUT_REVEALED"; } else report.verdict = "V3_DID_NOT_QUALIFY_SEALED_HOLDOUT_NOT_EVALUATED";
writeFileSync(path.join(output, "RESULTS.json"), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
