/** EUR/USD session-direction map: raw OANDA midpoint, no execution or trade rows. */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";

type Direction = "UP" | "DOWN"; type Candle = { time: string; close: number; high: number; low: number };
type Band = "near" | "moderate" | "far"; type Row = { session: "london" | "new_york"; band: Band; time: string; predicted: Direction; actual: Direction };
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."); for (const name of [".env", ".env.local"]) loadDotenv({ path: path.join(root, name), override: false });
const token = (process.env.OANDA_API_KEY ?? process.env.OANDA_API_TOKEN ?? "").trim().replace(/^["']|["']$/g, ""); if (!token) throw new Error("OANDA credentials are required");
const host = process.env.OANDA_ENVIRONMENT === "live" ? "https://api-fxtrade.oanda.com" : "https://api-fxpractice.oanda.com"; const pair = "EUR_USD";
const warmup = "2025-07-20T00:00:00.000Z"; const developmentStart = "2025-08-01T00:00:00.000Z"; const developmentEnd = "2026-04-01T00:00:00.000Z"; const holdoutEnd = "2026-08-01T00:00:00.000Z";
const distanceMap = process.env.EUR_USD_SESSION_MAP === "distance"; const output = path.join(root, "research-v2", distanceMap ? "eur-usd-session-distance-v1" : "eur-usd-session-direction-v1"); if (!existsSync(output)) mkdirSync(output, { recursive: true });
const london = new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/London", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }); const newYork = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hour: "2-digit", minute: "2-digit", hourCycle: "h23" });
function clock(format: Intl.DateTimeFormat, iso: string) { const parts = format.formatToParts(new Date(iso)); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? "00"; return { date: `${get("year")}-${get("month")}-${get("day")}`, minutes: Number(get("hour")) * 60 + Number(get("minute")) }; }
function lowerBound(correct: number, n: number, z = 2.576) { if (!n) return 0; const p = correct / n; return (p + z * z / (2 * n) - z * Math.sqrt((p * (1 - p) + z * z / (4 * n)) / n)) / (1 + z * z / n); }
function randomDirection(time: string, seed: number): Direction { let hash = 2166136261 ^ seed; for (const character of `${pair}|${time}`) hash = Math.imul(hash ^ character.charCodeAt(0), 16777619); hash ^= hash >>> 16; hash = Math.imul(hash, 0x85ebca6b); hash ^= hash >>> 13; hash = Math.imul(hash, 0xc2b2ae35); hash ^= hash >>> 16; return (hash >>> 0) % 2 === 0 ? "UP" : "DOWN"; }
async function fetchM15(end: string) { const seen = new Map<string, Candle>(); let cursor = warmup; for (let page = 0; page < 20; page++) { const response = await fetch(`${host}/v3/instruments/${pair}/candles?price=BA&granularity=M15&count=5000&from=${encodeURIComponent(cursor)}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`EUR_USD M15 fetch failed: ${response.status}`); const json = await response.json() as { candles?: Array<{ complete: boolean; time: string; bid: Record<string, string>; ask: Record<string, string> }> }; const batch = (json.candles ?? []).filter((bar) => bar.complete).map((bar) => { const midpoint = (key: string) => (+bar.bid[key]! + +bar.ask[key]!) / 2; return { time: new Date(Date.parse(bar.time) + 900_000).toISOString(), close: midpoint("c"), high: midpoint("h"), low: midpoint("l") }; }); for (const bar of batch) if (bar.time < end) seen.set(bar.time, bar); if (!batch.length || batch.length < 5000) break; cursor = batch.at(-1)!.time; if (Date.parse(cursor) >= Date.parse(end)) break; } return [...seen.values()].sort((a, b) => Date.parse(a.time) - Date.parse(b.time)); }
function rowsFor(bars: Candle[], from: string, to: string) { const rows: Row[] = []; for (let index = 36; index < bars.length - 4; index++) { const current = bars[index]!; if (current.time < from || current.time >= to) continue; const londonNow = clock(london, current.time); const nyNow = clock(newYork, current.time); const session = londonNow.minutes >= 8 * 60 && londonNow.minutes < 11 * 60 ? "london" : nyNow.minutes >= 8 * 60 && nyNow.minutes < 11 * 60 ? "new_york" : null; if (!session) continue; const asia = bars.slice(index - 36, index).filter((bar) => { const at = clock(london, bar.time); return at.date === londonNow.date && at.minutes < 7 * 60; }); if (asia.length < 24) continue; const high = Math.max(...asia.map((bar) => bar.high)); const low = Math.min(...asia.map((bar) => bar.low)); const predicted: Direction | null = current.close > high ? "UP" : current.close < low ? "DOWN" : null; const distance = !predicted || high === low ? 0 : (predicted === "UP" ? current.close - high : low - current.close) / (high - low); const band: Band = distance < 0.25 ? "near" : distance < 0.75 ? "moderate" : "far"; const future = bars[index + 4]!; if (!predicted || Date.parse(future.time) - Date.parse(current.time) !== 3_600_000 || future.close === current.close) continue; rows.push({ session, band, time: current.time, predicted, actual: future.close > current.close ? "UP" : "DOWN" }); } return rows; }
function score(rows: Row[], inverse = false) { const correct = rows.filter((row) => (inverse ? (row.predicted === "UP" ? "DOWN" : "UP") : row.predicted) === row.actual).length; const accuracy = rows.length ? correct / rows.length : 0; const random = Array.from({ length: 100 }, (_, seed) => rows.length ? rows.filter((row) => randomDirection(row.time, seed + 1) === row.actual).length / rows.length : 0).sort((a, b) => a - b); return { n: rows.length, correct, accuracy, lower99: lowerBound(correct, rows.length), randomControls: { count: 100, meanAccuracy: random.reduce((sum, value) => sum + value, 0) / random.length, p95Accuracy: random[94]! } }; }
const devBars = await fetchM15(new Date(Date.parse(developmentEnd) + 3_600_000).toISOString()); const developmentRows = rowsFor(devBars, developmentStart, developmentEnd); const groups = distanceMap ? ["near", "moderate", "far"] : ["london", "new_york"]; const development = groups.flatMap((group) => { const rows = distanceMap ? developmentRows.filter((row) => row.session === "london" && row.band === group) : developmentRows.filter((row) => row.session === group); return [{ name: distanceMap ? `london_${group}_continuation` : `${group}_continuation`, session: distanceMap ? "london" : group, band: distanceMap ? group : null, inverse: false, score: score(rows) }, { name: distanceMap ? `london_${group}_reversal` : `${group}_reversal`, session: distanceMap ? "london" : group, band: distanceMap ? group : null, inverse: true, score: score(rows, true) }]; });
const qualified = development.filter((candidate) => candidate.score.n >= 100 && candidate.score.accuracy > 0.5 && candidate.score.lower99 > 0.5 && candidate.score.accuracy > candidate.score.randomControls.p95Accuracy).sort((a, b) => b.score.lower99 - a.score.lower99)[0];
const report: Record<string, unknown> = { generatedAt: new Date().toISOString(), methodology: { source: "raw OANDA bid/ask midpoint M15 candles fetched at runtime", label: "midpoint direction 60 minutes after the completed decision candle", state: distanceMap ? "outside-range distance / Asian-range width: near <0.25, moderate 0.25-0.75, far >=0.75" : "current midpoint above or below the completed 00:00-07:00 Europe/London Asian range", sessions: distanceMap ? "London 08:00-11:00 Europe/London" : "London 08:00-11:00 Europe/London; New York 08:00-11:00 America/New_York", split: { development: "2025-08-01 through 2026-03-31", sealedHoldout: "2026-04-01 through 2026-07-31" }, gate: "n >= 100, accuracy > 50%, 99% Wilson lower bound > 50%, and above random p95", excluded: "entries, stops, targets, execution, trade rows, and database writes" }, development, verdict: qualified ? "QUALIFIED_FOR_SEALED_HOLDOUT" : "NO_SESSION_DIRECTION_QUALIFIED_HOLDOUT_REMAINS_UNREAD" };
if (qualified) { const holdBars = await fetchM15(new Date(Date.parse(holdoutEnd) + 3_600_000).toISOString()); const holdRows = rowsFor(holdBars, developmentEnd, holdoutEnd).filter((row) => row.session === qualified.session && (!qualified.band || row.band === qualified.band)); report.selected = { name: qualified.name, development: qualified.score, holdout: score(holdRows, qualified.inverse) }; }
writeFileSync(path.join(output, "RESULTS.json"), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
