/** Research-only historical replay of the current four-family strategy with a news-pause arm. */
import { config as env } from "dotenv"; import path from "node:path"; import { fileURLToPath } from "node:url"; import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { evaluateAllStrategies } from "../../frontend/src/lib/strategy/strategies/index.js";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."); env({path:path.join(root,".env")}); const key=(process.env.OANDA_API_KEY??process.env.OANDA_API_TOKEN??"").trim(); if(!key)throw Error("OANDA Practice credentials required"); if((process.env.OANDA_ENVIRONMENT??"practice")==="live")throw Error("No live research");
type Q={time:string;open:number;high:number;low:number;close:number;bid:any;ask:any;complete:boolean;volume:number}; const from="2024-08-01T00:00:00.000Z",to="2026-08-04T00:00:00.000Z";
async function fetch15(){let cur=from,m=new Map<string,Q>();for(let p=0;p<16;p++){const q=new URLSearchParams({price:"BA",granularity:"M15",count:"5000",from:cur}),r=await fetch(`https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles?${q}`,{headers:{Authorization:`Bearer ${key}`}});if(!r.ok)throw Error(`OANDA ${r.status}`);const j=await r.json() as any;const a=(j.candles??[]).filter((x:any)=>x.complete).map((x:any)=>{const mid=(k:string)=>(+x.bid[k]+ +x.ask[k])/2;return{time:new Date(Date.parse(x.time)+900000).toISOString(),open:mid("o"),high:mid("h"),low:mid("l"),close:mid("c"),bid:{o:+x.bid.o,h:+x.bid.h,l:+x.bid.l,c:+x.bid.c},ask:{o:+x.ask.o,h:+x.ask.h,l:+x.ask.l,c:+x.ask.c},complete:true,volume:+x.volume}});for(const x of a)if(x.time<to)m.set(x.time,x);if(!a.length||a.length<5000||a.at(-1).time>=to)break;cur=a.at(-1).time}return[...m.values()].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time))}
function agg(a:Q[],mins:number){const out:Q[]=[];for(let i=0;i<a.length;i+=mins){const s=a.slice(i,i+mins);if(s.length!==mins)continue;const x=s[0]!,z=s.at(-1)!;if(Date.parse(z.time)-Date.parse(x.time)!==(mins-1)*900000)continue;out.push({...z,time:z.time,open:x.open,high:Math.max(...s.map(v=>v.high)),low:Math.min(...s.map(v=>v.low)),close:z.close})}return out}
const events=["eurusd-ff-high-impact-aug2024-jul2025","eurusd-ff-high-impact-aug2025-jul2026"].flatMap(d=>(JSON.parse(readFileSync(path.join(root,"research-v2",d,"events.json"),"utf8")).events as any[]).map(e=>Date.parse(e.releaseTimeUtc))); const blocked=(t:number)=>events.some(e=>t>=e-30*60000&&t<=e+60*60000);
function resolve(a:Q[],i:number,c:any){for(let j=i+1;j<a.length&&j<i+96;j++){const x=a[j],long=c.direction==="long",tp=long?x.bid.h>=c.target:x.ask.l<=c.target,sl=long?x.bid.l<=c.stop:x.ask.h>=c.stop;if(tp&&sl)return-1;if(tp)return 1.5;if(sl)return-1}return 0}
const a=await fetch15(),h=agg(a,4),h4=agg(a,16);let hi=0,fi=0;const rows:any[]=[];for(let i=210;i<a.length-96;i++){const t=Date.parse(a[i].time);while(hi<h.length-1&&Date.parse(h[hi+1].time)<=t)hi++;while(fi<h4.length-1&&Date.parse(h4[fi+1].time)<=t)fi++;if(hi<210||fi<210)continue;const input:any={instrument:"EUR_USD",accountBalance:10000,accountCurrency:"USD",dataSource:"oanda",candles15m:a.slice(i-209,i+1),candles1h:h.slice(hi-209,hi+1),candles4h:h4.slice(fi-209,fi+1),bid:a[i].bid.c,ask:a[i].ask.c,spreadPips:(a[i].ask.c-a[i].bid.c)*10000,marketOpen:true,calendarConnected:true,highImpactNewsWithinMinutes:null,evaluatedAt:a[i].time};for(const c of evaluateAllStrategies(input).candidates)if(c.status==="valid"&&c.entry&&c.stop&&c.target)rows.push({family:c.family,time:a[i].time,blocked:blocked(t),r:resolve(a,i,c)})}
const sum=(x:any[])=>({trades:x.length,wins:x.filter(v=>v.r>0).length,winRate:x.length?x.filter(v=>v.r>0).length/x.length:null,expectancyR:x.length?x.reduce((s,v)=>s+v.r,0)/x.length:null});const report={generatedAt:new Date().toISOString(),scope:{source:"raw OANDA Practice M15; H1/H4 aggregated from completed M15",newsPause:"30m before to 60m after supplied high-impact EUR/USD release",resolver:"bid/ask, 1.5R target/1R stop, 24h max; ambiguous bar charged stop"},byFamily:Object.fromEntries(["ema","breakout","momentum","meanrev"].map(f=>[f,{normal:sum(rows.filter(r=>r.family===f)),newsPaused:sum(rows.filter(r=>r.family===f&&!r.blocked)),excluded:rows.filter(r=>r.family===f&&r.blocked).length}]))};const out=path.join(root,"research-v2","four-family-news-pause-v1");mkdirSync(out,{recursive:true});writeFileSync(path.join(out,"RESULTS.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
