/** Research-only bid/ask execution replay for the frozen EUR/USD news-surprise rule. */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";
type E={releaseTimeUtc:string;currency:"EUR"|"USD";eventName:string;actual:string;forecast:string}; type C={events:E[]};
type B={time:string;bid:{o:number;h:number;l:number;c:number};ask:{o:number;h:number;l:number;c:number}}; type S={e:E;d:1|-1}; type G={time:string;d:1|-1}; type T={r:number;outcome:string;ambiguous:boolean;atrPips:number;spreadPips:number;spreadConsumesStop:boolean};
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."); for(const n of [".env",".env.local"])loadDotenv({path:path.join(root,n),override:false}); const token=(process.env.OANDA_API_KEY??process.env.OANDA_API_TOKEN??"").trim().replace(/^["']|["']$/g,""); if(!token)throw Error("OANDA Practice credentials are required."); if((process.env.OANDA_ENVIRONMENT??"practice").toLowerCase()==="live")throw Error("This research replay refuses OANDA live.");
const files=[path.join(root,"research-v2","eurusd-ff-high-impact-aug2024-jul2025","events.json"),path.join(root,"research-v2","eurusd-ff-high-impact-aug2025-jul2026","events.json")], output=path.join(root,"research-v2","eurusd-news-surprise-day-swing-v1");
const num=(v:string)=>{const m=v.trim().replace(/,/g,"").match(/^(-?\d+(?:\.\d+)?)\s*([KMB%])?$/i);return m?{v:+m[1],u:(m[2]??"").toUpperCase()}:null};
function kind(e:E){if(/Unemployment (Rate|Claims)/.test(e.eventName))return"labor"; if(/(CPI|PPI|PCE|Federal Funds Rate|Main Refinancing Rate)/.test(e.eventName))return"inflation"; return /(Employment Change|Hourly Earnings|GDP|PMI|Job Openings|Retail Sales|Employment Cost|Consumer Sentiment)/.test(e.eventName)?"growth":null}
function signal(e:E):S|null{const a=num(e.actual),f=num(e.forecast),k=kind(e); if(!a||!f||!k||k==="inflation"||a.u!==f.u||a.v===f.v)return null; const good=(a.v>f.v?1:-1)*(k==="labor"?-1:1);return{e,d:(good*(e.currency==="EUR"?1:-1))as 1|-1}}
async function bars(from:string,to:string){const m=new Map<string,B>();let cur=from;for(let p=0;p<45;p++){const q=new URLSearchParams({price:"BA",granularity:"M5",count:"5000",from:cur}),res=await fetch(`https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles?${q}`,{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)throw Error(`OANDA M5 fetch ${res.status}`);const j=await res.json() as {candles?:Array<{complete:boolean;time:string;bid:Record<string,string>;ask:Record<string,string>}>};const page=(j.candles??[]).filter(x=>x.complete).map(x=>({time:new Date(Date.parse(x.time)+300000).toISOString(),bid:{o:+x.bid.o,h:+x.bid.h,l:+x.bid.l,c:+x.bid.c},ask:{o:+x.ask.o,h:+x.ask.h,l:+x.ask.l,c:+x.ask.c}}));for(const b of page)if(b.time<to)m.set(b.time,b);if(!page.length||page.length<5000||page.at(-1)!.time>=to)break;cur=page.at(-1)!.time}return[...m.values()].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time))}
function atr14(b:B[],i:number){let sum=0;for(let j=i-13;j<=i;j++){const x=b[j]!,p=b[j-1]!,hi=(x.bid.h+x.ask.h)/2,lo=(x.bid.l+x.ask.l)/2,pc=(p.bid.c+p.ask.c)/2;sum+=Math.max(hi-lo,Math.abs(hi-pc),Math.abs(lo-pc))}return sum/14}
function nyEnd(ms:number){const fmt=new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hourCycle:"h23"}),wanted=fmt.formatToParts(ms).filter(x=>x.type!=="hour").map(x=>x.value).join("");for(let h=20;h<=23;h++)for(let min=0;min<60;min+=5){const t=Date.UTC(new Date(ms).getUTCFullYear(),new Date(ms).getUTCMonth(),new Date(ms).getUTCDate(),h,min);const parts=fmt.formatToParts(t),day=parts.filter(x=>x.type!=="hour").map(x=>x.value).join(""),hour=parts.find(x=>x.type==="hour")?.value;if(day===wanted&&hour==="17")return t}return ms+12*3600000}
function resolve(b:B[],entryI:number,d:1|-1,until:number,a:number):T|null{if(!Number.isFinite(a)||a<=0)return null;const entry=d===1?b[entryI]!.ask.c:b[entryI]!.bid.c,stop=d===1?entry-.75*a:entry+.75*a,target=d===1?entry+1.5*a:entry-1.5*a,meta={atrPips:a*10000,spreadPips:(b[entryI]!.ask.c-b[entryI]!.bid.c)*10000,spreadConsumesStop:(b[entryI]!.ask.c-b[entryI]!.bid.c)>=.75*a};for(let i=entryI;i<b.length&&Date.parse(b[i]!.time)<=until;i++){const x=b[i]!,tp=d===1?x.bid.h>=target:x.ask.l<=target,sl=d===1?x.bid.l<=stop:x.ask.h>=stop;if(tp&&sl)return{...meta,r:-.75,outcome:"AMBIGUOUS_CONSERVATIVE_STOP",ambiguous:true};if(tp)return{...meta,r:1.5,outcome:"TARGET",ambiguous:false};if(sl)return{...meta,r:-.75,outcome:"STOP",ambiguous:false}}let last=-1;for(let i=entryI;i<b.length&&Date.parse(b[i]!.time)<=until;i++)last=i;if(last<0)return null;const exit=d===1?b[last]!.bid.c:b[last]!.ask.c;return{...meta,r:(d===1?exit-entry:entry-exit)/a,outcome:"TIME_EXIT",ambiguous:false}}
const events=files.flatMap(f=>(JSON.parse(readFileSync(f,"utf8"))as C).events), signals=events.map(signal).filter((x):x is S=>!!x),by=new Map<string,S[]>();for(const s of signals)by.set(s.e.releaseTimeUtc,[...(by.get(s.e.releaseTimeUtc)??[]),s]);const groups:G[]=[];for(const[time,x]of by){const vote=x.reduce((n,s)=>n+s.d,0);if(vote)groups.push({time,d:(vote>0?1:-1)as 1|-1})}groups.sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));const chosen:G[]=[];for(const g of groups){const p=chosen.at(-1);if(!p||Date.parse(g.time)>=Date.parse(p.time)+4*3600000)chosen.push(g)}const b=await bars("2024-08-01T00:00:00.000Z","2026-08-04T00:00:00.000Z"),idx=new Map(b.map((x,i)=>[x.time,i]));
function run(mode:"day"|"swing",delayMinutes:number){const rows=chosen.flatMap(g=>{const rel=Date.parse(g.time),baseI=idx.get(g.time),i=idx.get(new Date(rel+delayMinutes*60000).toISOString());if(i===undefined||baseI===undefined||baseI<14)return[];const t=resolve(b,i,g.d,mode==="day"?nyEnd(rel):rel+72*3600000,atr14(b,baseI));return t?[t]:[]}),wins=rows.filter(x=>x.r>0).length,total=rows.reduce((n,x)=>n+x.r,0),median=(v:number[])=>v.sort((a,b)=>a-b)[Math.floor(v.length/2)]??null;return{trades:rows.length,wins,winRate:rows.length?wins/rows.length:null,totalR:total,expectancyR:rows.length?total/rows.length:null,targetHits:rows.filter(x=>x.outcome==="TARGET").length,stops:rows.filter(x=>x.outcome.includes("STOP")).length,timeExits:rows.filter(x=>x.outcome==="TIME_EXIT").length,ambiguousConservativeStops:rows.filter(x=>x.ambiguous).length,medianPreNewsAtrPips:median(rows.map(x=>x.atrPips)),medianEntrySpreadPips:median(rows.map(x=>x.spreadPips)),spreadsAtLeastStopDistance:rows.filter(x=>x.spreadConsumesStop).length}}
const resultFor=(delayMinutes:number)=>({day:run("day",delayMinutes),swing:run("swing",delayMinutes)});const report={generatedAt:new Date().toISOString(),verdict:"RESEARCH_ONLY_NO_PROMOTION",scope:{signal:"frozen 2024-26 non-inflation/rate EUR/USD economic-surprise direction rule",entry:"completed M5 candle at the stated delay after release; long enters ask, short enters bid",riskUnit:"1.0 = ATR14 of completed pre-release M5 midpoint candles, fixed before the release",exit:"long exits/levels use bid; short exits/levels use ask",target:1.5,stop:-.75,day:"exit no later than 5pm New York time",swing:"exit no later than 72 hours",ambiguous:"if both stop and target fall inside one M5 candle, charged as stop",excludes:"live/paper orders and any post-result tuning"},signals:{rawNumericSignals:signals.length,nonOverlappingFourHourSignals:chosen.length},results:{delay5m:resultFor(5),delay15m:resultFor(15),delay30m:resultFor(30)}};mkdirSync(output,{recursive:true});writeFileSync(path.join(output,"RESULTS.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
function structural(){const r:any[]=[];for(const g of chosen){const t=Date.parse(g.time),bi=idx.get(g.time),i=idx.get(new Date(t+900000).toISOString());if(bi===undefined||i===undefined||bi<14||atr14(b,bi)*10000>5.53)continue;const c=b[i]!,mid=(c.bid.c+c.ask.c)/2,pre=(b[bi]!.bid.c+b[bi]!.ask.c)/2;if((g.d===1?mid>pre:mid<pre)===false)continue;const entry=g.d===1?c.ask.c:c.bid.c,stop=g.d===1?c.bid.l:c.ask.h,risk=Math.abs(entry-stop);if(!risk)continue;const target=g.d===1?entry+1.5*risk:entry-1.5*risk;let out=-1;for(let j=i+1;j<b.length&&Date.parse(b[j]!.time)<=t+72*3600000;j++){const x=b[j]!,tp=g.d===1?x.bid.h>=target:x.ask.l<=target,sl=g.d===1?x.bid.l<=stop:x.ask.h>=stop;if(tp&&sl){out=-1;break}if(tp){out=1.5;break}if(sl)break}r.push(out)}const w=r.filter(x=>x>0).length;return{trades:r.length,wins:w,winRate:r.length?w/r.length:null,totalR:r.reduce((a,x)=>a+x,0),expectancyR:r.length?r.reduce((a,x)=>a+x,0)/r.length:null}}
const structuralReport={scope:"low K-means ATR regime; 15m confirmation agrees; structural wick stop; 1.5x target; bid/ask; 72h",result:structural()};writeFileSync(path.join(output,"STRUCTURAL_LOW_VOL_RESULTS.json"),JSON.stringify(structuralReport,null,2));console.log(JSON.stringify(structuralReport,null,2));
