/** EUR/USD-only, four-hour, expanding-window trend learner. Research only. */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";

type Bar = { time: string; close: number; high: number; low: number };
type Row = { time: string; y: 0 | 1; x: number[] };
type Model = { mean: number[]; scale: number[]; weights: number[]; bias: number };
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
for (const name of [".env", ".env.local"]) loadDotenv({ path: path.join(root, name), override: false });
const token = (process.env.OANDA_API_KEY ?? process.env.OANDA_API_TOKEN ?? "").trim().replace(/^["']|["']$/g, "");
if (!token) throw new Error("OANDA Practice credentials are required.");
if ((process.env.OANDA_ENVIRONMENT ?? "practice").trim().toLowerCase() === "live") throw new Error("This research replay refuses OANDA live.");
const output = path.join(root, "research-v2", "eur-usd-4h-trend-learner-v1");
const start = "2022-08-01T00:00:00.000Z", end = "2026-08-01T00:00:00.000Z";
const folds = ["2023-08-01T00:00:00.000Z", "2024-02-01T00:00:00.000Z", "2024-08-01T00:00:00.000Z", "2025-02-01T00:00:00.000Z", "2025-08-01T00:00:00.000Z", "2026-02-01T00:00:00.000Z"];
const TEST_MONTHS = 6, CONFIDENCE_MARGIN = 0.02;

function sigmoid(v: number) { return v >= 0 ? 1 / (1 + Math.exp(-v)) : Math.exp(v) / (1 + Math.exp(v)); }
function ema(values: number[], n: number) { const out = [values[0]!], k = 2 / (n + 1); for (let i = 1; i < values.length; i++) out.push(values[i]! * k + out[i - 1]! * (1 - k)); return out; }
function atr(bars: Bar[], n = 14) { const out = new Array<number>(bars.length).fill(NaN); let v = 0; for (let i = 0; i < bars.length; i++) { const b = bars[i]!, p = bars[i - 1]; const tr = p ? Math.max(b.high - b.low, Math.abs(b.high - p.close), Math.abs(b.low - p.close)) : b.high - b.low; if (i < n) { v += tr; if (i === n - 1) out[i] = v / n; } else { v = ((out[i - 1]! * (n - 1)) + tr) / n; out[i] = v; } } return out; }
function slope(values: number[]) { const mx = (values.length - 1) / 2, my = values.reduce((a, b) => a + b, 0) / values.length; let n = 0, d = 0; for (let i = 0; i < values.length; i++) { n += (i - mx) * (values[i]! - my); d += (i - mx) ** 2; } return d ? n / d : 0; }
async function fetchH1() { const all = new Map<string, Bar>(); let cursor = start; for (let page = 0; page < 20; page += 1) { const q = new URLSearchParams({ price: "BA", granularity: "H1", count: "5000", from: cursor }); const response = await fetch(`https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles?${q}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`OANDA H1 fetch failed: ${response.status}`); const payload = await response.json() as { candles?: Array<{ complete: boolean; time: string; bid: Record<string, string>; ask: Record<string, string> }> }; const pageBars = (payload.candles ?? []).filter((b) => b.complete).map((b) => { const mid = (key: string) => (Number(b.bid[key]) + Number(b.ask[key])) / 2; return { time: new Date(Date.parse(b.time) + 3_600_000).toISOString(), close: mid("c"), high: mid("h"), low: mid("l") }; }); for (const b of pageBars) if (b.time < end) all.set(b.time, b); if (pageBars.length < 5000 || !pageBars.length) break; cursor = pageBars.at(-1)!.time; if (cursor >= end) break; } return [...all.values()].sort((a, b) => Date.parse(a.time) - Date.parse(b.time)); }
function rowsFrom(bars: Bar[]) { const close = bars.map((b) => b.close), a14 = atr(bars, 14), a48 = atr(bars, 48), e8 = ema(close, 8), e21 = ema(close, 21), e50 = ema(close, 50); const rows: Row[] = []; for (let i = 48; i < bars.length - 4; i++) { const b = bars[i]!, future = bars[i + 4]!; const d = new Date(b.time); if (b.time < "2022-09-01T00:00:00.000Z" || d.getUTCHours() % 4 !== 0 || !Number.isFinite(a14[i]) || !Number.isFinite(a48[i]) || future.close === b.close) continue; const unit = a14[i]!, w = bars.slice(i - 23, i + 1), lo = Math.min(...w.map((x) => x.low)), hi = Math.max(...w.map((x) => x.high)); rows.push({ time: b.time, y: future.close > b.close ? 1 : 0, x: [(b.close - bars[i - 4]!.close) / unit, (b.close - bars[i - 12]!.close) / unit, slope(close.slice(i - 23, i + 1)) / unit, (e8[i]! - e21[i]!) / unit, (e21[i]! - e50[i]!) / unit, hi === lo ? 0 : (b.close - lo) / (hi - lo) - .5, a14[i]! / a48[i]!] }); } return rows; }
function fit(rows: Row[]): Model { const n = rows[0]!.x.length, mean = Array.from({ length: n }, (_, j) => rows.reduce((s, r) => s + r.x[j]!, 0) / rows.length), scale = mean.map((m, j) => Math.max(1e-8, Math.sqrt(rows.reduce((s, r) => s + (r.x[j]! - m) ** 2, 0) / rows.length))); const weights = new Array<number>(n).fill(0); let bias = 0; for (let epoch = 0; epoch < 700; epoch++) { const g = new Array<number>(n).fill(0); let gb = 0; for (const r of rows) { const x = r.x.map((v, j) => (v - mean[j]!) / scale[j]!); const error = sigmoid(bias + x.reduce((s, v, j) => s + v * weights[j]!, 0)) - r.y; for (let j = 0; j < n; j++) g[j] += error * x[j]!; gb += error; } for (let j = 0; j < n; j++) weights[j] -= .04 * (g[j]! / rows.length + .03 * weights[j]!); bias -= .04 * gb / rows.length; } return { mean, scale, weights, bias }; }
function p(model: Model, row: Row) { return sigmoid(model.bias + row.x.reduce((s, v, j) => s + ((v - model.mean[j]!) / model.scale[j]!) * model.weights[j]!, 0)); }
function hash(time: string, seed: number) { let h = 2166136261 ^ seed; for (const c of time) h = Math.imul(h ^ c.charCodeAt(0), 16777619); h ^= h >>> 16; h = Math.imul(h, 0x85ebca6b); h ^= h >>> 13; h = Math.imul(h, 0xc2b2ae35); h ^= h >>> 16; return h >>> 0; }
function score(model: Model, rows: Row[]) { const selected = rows.filter((r) => Math.abs(p(model, r) - .5) >= CONFIDENCE_MARGIN); const correct = selected.filter((r) => (p(model, r) >= .5 ? 1 : 0) === r.y).length; const random = Array.from({ length: 100 }, (_, seed) => selected.length ? selected.filter((r) => (hash(r.time, seed + 1) & 1) === r.y).length / selected.length : 0).sort((a, b) => a - b); return { total: rows.length, selected: selected.length, abstained: rows.length - selected.length, accuracy: selected.length ? correct / selected.length : null, inverseAccuracy: selected.length ? 1 - correct / selected.length : null, randomMean: random.reduce((a, b) => a + b, 0) / random.length, randomP95: random[94]! }; }
function addMonths(iso: string, months: number) { const date = new Date(iso); date.setUTCMonth(date.getUTCMonth() + months); return date.toISOString(); }

const bars = await fetchH1(); const rows = rowsFrom(bars); console.log(`[trend-learner] ${bars.length} H1 candles, ${rows.length} independent 4h labels`);
const results = folds.map((cutoff) => { const train = rows.filter((r) => r.time < cutoff); const testEnd = addMonths(cutoff, TEST_MONTHS); const test = rows.filter((r) => r.time >= cutoff && r.time < testEnd); return { trainEnd: cutoff, testEnd, train: train.length, test: score(fit(train), test) }; });
const report = { generatedAt: new Date().toISOString(), verdict: "RESEARCH_ONLY_NO_PROMOTION", scope: { instrument: "EUR_USD", source: "raw OANDA Practice H1 bid/ask midpoint candles", decisions: "non-overlapping UTC 4-hour closes", label: "next four-hour midpoint close UP or DOWN", model: "frozen L2 logistic regression, retrained only on data before each six-month test fold", features: ["4h and 12h ATR-normalized returns", "24h slope and range position", "EMA8-21 and EMA21-50 spreads", "ATR14/ATR48 volatility ratio"], abstention: `WAIT unless |p(UP)-0.5| >= ${CONFIDENCE_MARGIN}`, controls: "exact inverse and 100 seeded random directions", excludes: "trades, stop/target profitability, execution, calendar, and production/paper orders" }, folds: results, latestSealedFold: results.at(-1) };
mkdirSync(output, { recursive: true }); writeFileSync(path.join(output, "RESULTS.json"), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
