/**
 * Independent historical validation of the frozen EUR/USD moderate-extension
 * London reversal hypothesis. Reads only OANDA bid/ask market quotes, never
 * trade rows; the 2026 sealed period is excluded.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";

type Direction = "UP" | "DOWN"; type Candle = { time: string; close: number; high: number; low: number }; type Row = { time: string; predicted: Direction; actual: Direction };
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."); for (const name of [".env", ".env.local"]) loadDotenv({ path: path.join(root, name), override: false }); if (process.env.DATABASE_PUBLIC_URL) process.env.DATABASE_URL = process.env.DATABASE_PUBLIC_URL;
const { query } = await import("../src/database.js"); const output = path.join(root, "research-v2", "eur-usd-moderate-reversal-independent-history"); if (!existsSync(output)) mkdirSync(output, { recursive: true });
const start = "2016-04-04T00:00:00.000Z"; const end = "2025-08-01T00:00:00.000Z"; const london = new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/London", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" });
function clock(iso: string) { const parts = london.formatToParts(new Date(iso)); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? "00"; return { year: get("year"), date: `${get("year")}-${get("month")}-${get("day")}`, minutes: Number(get("hour")) * 60 + Number(get("minute")) }; }
function lower99(correct: number, n: number) { if (!n) return 0; const z = 2.576; const p = correct / n; return (p + z * z / (2 * n) - z * Math.sqrt((p * (1 - p) + z * z / (4 * n)) / n)) / (1 + z * z / n); }
function randomDirection(time: string, seed: number): Direction { let hash = 2166136261 ^ seed; for (const character of `EUR_USD|${time}`) hash = Math.imul(hash ^ character.charCodeAt(0), 16777619); hash ^= hash >>> 16; hash = Math.imul(hash, 0x85ebca6b); hash ^= hash >>> 13; hash = Math.imul(hash, 0xc2b2ae35); hash ^= hash >>> 16; return (hash >>> 0) % 2 === 0 ? "UP" : "DOWN"; }
function score(rows: Row[]) { const correct = rows.filter((row) => row.actual === row.predicted).length; const accuracy = rows.length ? correct / rows.length : 0; const random = Array.from({ length: 100 }, (_, seed) => rows.length ? rows.filter((row) => randomDirection(row.time, seed + 1) === row.actual).length / rows.length : 0).sort((a, b) => a - b); return { n: rows.length, correct, accuracy, lower99: lower99(correct, rows.length), randomControls: { count: 100, meanAccuracy: random.reduce((sum, value) => sum + value, 0) / random.length, p95Accuracy: random[94]! } }; }
const records = await query<{ close_time: string; bid_close: number; ask_close: number; bid_high: number; ask_high: number; bid_low: number; ask_low: number }>(`SELECT close_time::text,bid_close::float,ask_close::float,bid_high::float,ask_high::float,bid_low::float,ask_low::float FROM market_candle_quotes WHERE instrument='EUR_USD' AND timeframe='M15' AND source='oanda' AND close_time >= $1 AND close_time < $2 ORDER BY close_time`, [start, end]);
const bars: Candle[] = records.rows.map((row) => ({ time: new Date(row.close_time).toISOString(), close: (row.bid_close + row.ask_close) / 2, high: (row.bid_high + row.ask_high) / 2, low: (row.bid_low + row.ask_low) / 2 })); const rows: Row[] = [];
for (let index = 36; index < bars.length - 4; index++) { const current = bars[index]!; const at = clock(current.time); if (at.minutes < 8 * 60 || at.minutes >= 11 * 60) continue; const asia = bars.slice(index - 36, index).filter((bar) => { const time = clock(bar.time); return time.date === at.date && time.minutes < 7 * 60; }); if (asia.length < 24) continue; const high = Math.max(...asia.map((bar) => bar.high)); const low = Math.min(...asia.map((bar) => bar.low)); const predicted: Direction | null = current.close > high ? "DOWN" : current.close < low ? "UP" : null; const outside = current.close > high ? current.close - high : current.close < low ? low - current.close : 0; const distance = high === low ? 0 : outside / (high - low); if (!predicted || distance < 0.25 || distance >= 0.75) continue; const future = bars[index + 4]!; if (Date.parse(future.time) - Date.parse(current.time) !== 3_600_000 || future.close === current.close) continue; rows.push({ time: current.time, predicted, actual: future.close > current.close ? "UP" : "DOWN" }); }
const byYear = Object.fromEntries([...new Set(rows.map((row) => clock(row.time).year))].map((year) => { const subset = rows.filter((row) => clock(row.time).year === year); return [year, score(subset)]; })); const overall = score(rows); const report = { generatedAt: new Date().toISOString(), hypothesis: "EUR/USD London 08:00-11:00 moderate (0.25-0.75 Asian-range widths) extension reverses over the next 60 minutes", methodology: { source: "stored OANDA bid/ask M15 market quotes", independentPeriod: `${start} through ${end}`, excluded: "all trade rows, all execution metrics, and the 2025-08 onward discovery/holdout period", label: "DOWN when price is above Asian range, UP when below; resolved by midpoint after 60 minutes", passGate: "99% lower confidence >50% and above random p95" }, coverage: { candles: bars.length, rows: rows.length }, overall, byYear, verdict: overall.accuracy > 0.5 && overall.lower99 > 0.5 && overall.accuracy > overall.randomControls.p95Accuracy ? "INDEPENDENT_HISTORY_SUPPORTS_HYPOTHESIS" : "INDEPENDENT_HISTORY_DOES_NOT_SUPPORT_HYPOTHESIS" };
writeFileSync(path.join(output, "RESULTS.json"), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
