// Exact frozen TradingView cohort replay. RESEARCH_ONLY / PRACTICE_ONLY.
import fs from 'node:fs';
import path from 'node:path';
import { config } from 'dotenv';

const SOURCE = 'C:/Users/arche/Downloads/GX_GBPNZD_06UTC_Bull_Consensus_V1_-_1_to_2_RR_OANDA_GBPNZD_2026-09-07_38a1f.csv';
const PINE = 'C:/Users/arche/.codex/attachments/5d3a5cd5-3ca3-4806-bcf8-1bb384166880/pasted-text.txt';
const BASE = path.resolve('research-v2/gbpnzd-06utc-bull-consensus-v1-spread-validation');
const DATA = path.join(BASE, 'data');
const INSTRUMENT = 'GBP_NZD', PIP = 10_000, H = 3_600_000, M = 60_000;
type Candle = { t:number; bo:number; bh:number; bl:number; bc:number; ao:number; ah:number; al:number; ac:number };
type Trade = { n:number; entryWall:string; exitWall:string; entry:number; exit:number; signal:string; exitLabel:string; duration:number; entryMs:number; exitMs:number };

function nyOffset(utc:number) { const f=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}); const p:any={}; for(const x of f.formatToParts(new Date(utc))) p[x.type]=x.value; return Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-utc; }
function nyUtc(s:string) { const [d,t]=s.trim().split(' '),[y,mo,da]=d.split('-').map(Number),[h,mi]=t.split(':').map(Number); const g=Date.UTC(y,mo-1,da,h,mi); const u=g-nyOffset(g); return g-nyOffset(u); }
function parseCsvLine(line:string) { const a:string[]=[]; let s='',q=false; for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(s);s='';}else s+=c;} a.push(s); return a; }
function cohort():Trade[] { const rows=fs.readFileSync(SOURCE,'utf8').replace(/^\uFEFF/,'').trim().split(/\r?\n/).slice(1).map(parseCsvLine); const groups=new Map<string,string[][]>(); for(const row of rows) groups.set(row[0],[...(groups.get(row[0])??[]),row]); const out:Trade[]=[]; for(const [id,legs] of groups){const e=legs.find(x=>x[1].startsWith('Entry')),x=legs.find(x=>x[1].startsWith('Exit'));if(!e||!x)throw Error(`trade ${id}: incomplete CSV legs`);out.push({n:+id,entryWall:e[2],exitWall:x[2],entry:+e[4],exit:+x[4],signal:e[3],exitLabel:x[3],duration:+x[16],entryMs:nyUtc(e[2]),exitMs:nyUtc(x[2])});} return out.sort((a,b)=>a.n-b.n); }
function ema(v:number[],n:number){const out:(number|null)[]=Array(v.length).fill(null),k=2/(n+1);let prev=0;for(let i=0;i<v.length;i++){if(i<n-1)continue;if(i===n-1)prev=v.slice(0,n).reduce((a,b)=>a+b,0)/n;else prev=k*v[i]+(1-k)*prev;out[i]=prev;}return out;}
function atr(h:number[],l:number[],c:number[]){const out:(number|null)[]=Array(c.length).fill(null),tr=c.map((v,i)=>i?Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])):0);let prev=0;for(let i=1;i<c.length;i++){if(i<14)continue;if(i===14)prev=tr.slice(1,15).reduce((a,b)=>a+b,0)/14;else prev=(prev*13+tr[i])/14;out[i]=prev;}return out;}
function sum(a:number[]){return a.reduce((x,y)=>x+y,0)} function avg(a:number[]){return a.length?sum(a)/a.length:0} function med(a:number[]){const x=[...a].sort((p,q)=>p-q),i=x.length>>1;return x.length?x.length%2?x[i]:(x[i-1]+x[i])/2:0}
function stats(rs:number[]){const w=rs.filter(x=>x>0),l=rs.filter(x=>x<=0),gp=sum(w),gl=Math.abs(sum(l));return{n:rs.length,wins:w.length,losses:l.length,wr:rs.length?100*w.length/rs.length:0,pf:gl?gp/gl:null,total:sum(rs),expectancy:avg(rs),averageWinner:avg(w),averageLoser:avg(l)};}
function drawdown(rs:number[]){let equity=0,peak=0,max=0;for(const r of rs){equity+=r;peak=Math.max(peak,equity);max=Math.max(max,peak-equity)}return max;}
function compact(x:any):Candle{return{t:Date.parse(x.time),bo:+x.bid.o,bh:+x.bid.h,bl:+x.bid.l,bc:+x.bid.c,ao:+x.ask.o,ah:+x.ask.h,al:+x.ask.l,ac:+x.ask.c};}
async function collect(trades:Trade[]){config({path:path.resolve('.env'),quiet:true});config({path:path.resolve('.env.local'),quiet:true});if((process.env.OANDA_ENVIRONMENT??'').toLowerCase()==='live')throw Error('Practice-only validation refuses a live OANDA environment');const token=(process.env.OANDA_API_KEY??process.env.OANDA_API_TOKEN??'').trim().replace(/^["']|["']$/g,'');if(!token)throw Error('Missing OANDA_API_KEY');fs.mkdirSync(DATA,{recursive:true});
 async function req(url:string){for(let attempt=0;attempt<5;attempt++){try{const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(30_000)});if(r.ok)return r.json();if(![429,500,502,503,504].includes(r.status))throw Error(`OANDA HTTP ${r.status}`);}catch(e){if(attempt===4)throw e;}await new Promise(r=>setTimeout(r,400*(attempt+1)));}throw Error('OANDA retry exhaustion');}
 async function range(g:'H1'|'M1',from:number,to:number){const step=g==='H1'?H:M,out:Candle[]=[];for(let at=from;at<to;){const url=`https://api-fxpractice.oanda.com/v3/instruments/${INSTRUMENT}/candles?price=MBA&granularity=${g}&count=5000&from=${encodeURIComponent(new Date(at).toISOString())}`;const b=await req(url),candles=(b.candles??[]).filter((x:any)=>x.complete&&x.bid&&x.ask);if(!candles.length)break;for(const x of candles){const c=compact(x);if(c.t<to)out.push(c);}const next=Date.parse(candles.at(-1).time)+step;if(next<=at)break;at=next;}return out;}
 async function cached(g:'H1'|'M1',from:number,to:number,file:string){if(fs.existsSync(file))return JSON.parse(fs.readFileSync(file,'utf8')).candles as Candle[];const values=await range(g,from,to),unique=[...new Map(values.map(x=>[x.t,x])).values()].sort((a,b)=>a.t-b.t);fs.writeFileSync(file,JSON.stringify({instrument:INSTRUMENT,granularity:g,candles:unique},null,2));return unique;}
 const last=Math.max(...trades.map(x=>x.entryMs));const h1=await cached('H1',Date.UTC(2022,5,1),last+5*86400000,path.join(DATA,`${INSTRUMENT}-H1-MBA.json`));const minuteFile=path.join(DATA,`${INSTRUMENT}-M1-MBA.json`);if(fs.existsSync(minuteFile))return{h1,m1:JSON.parse(fs.readFileSync(minuteFile,'utf8')).candles as Candle[]};let parts:Candle[]=[];for(const t of trades)parts.push(...await range('M1',t.entryMs+H,t.entryMs+4*H));const m1=[...new Map(parts.map(x=>[x.t,x])).values()].sort((a,b)=>a.t-b.t);fs.writeFileSync(minuteFile,JSON.stringify({instrument:INSTRUMENT,granularity:'M1',candles:m1},null,2));return{h1,m1};
}
function esc(v:any){const s=v==null?'':String(v);return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function writeCsv(name:string,rows:any[],columns:string[]){fs.writeFileSync(path.join(BASE,name),[columns.join(','),...rows.map(r=>columns.map(c=>esc(r[c])).join(','))].join('\n')+'\n');}
function fmt(n:number|null,d=4){return n==null?'N/A':Number.isFinite(n)?n.toFixed(d):'∞';}
function classify(x:number){return x>=.15?'STRONG':x>=.10?'GOOD':x>=.05?'WEAK':x>=0?'NO_EDGE':'LOSING';}
function yearStatus(x:number){return x>0?'POSITIVE':x<0?'NEGATIVE':'FLAT';}

async function main(){
 fs.mkdirSync(BASE,{recursive:true});fs.copyFileSync(SOURCE,path.join(BASE,'TRADINGVIEW_SOURCE.csv'));fs.copyFileSync(PINE,path.join(BASE,'FROZEN_STRATEGY.pine'));
 const trades=cohort();if(trades.length!==216)throw Error(`Expected exactly 216 TradingView trades, found ${trades.length}`);for(const t of trades)if(t.signal!=='GBPNZD_0600_LONG'||new Date(t.entryMs).getUTCHours()!==6)throw Error(`Trade ${t.n} violates frozen 06:00 UTC origin (${t.signal}, ${new Date(t.entryMs).toISOString()})`);
 const {h1,m1}=await collect(trades);const mid=h1.map(q=>({t:q.t,o:(q.bo+q.ao)/2,h:(q.bh+q.ah)/2,l:(q.bl+q.al)/2,c:(q.bc+q.ac)/2})),index=new Map(mid.map((q,i)=>[q.t,i])),minutes=new Map(m1.map(q=>[q.t,q]));const e20=ema(mid.map(x=>x.c),20),e50=ema(mid.map(x=>x.c),50),a14=atr(mid.map(x=>x.h),mid.map(x=>x.l),mid.map(x=>x.c));const rows:any[]=[],parity:any={consensusFailures:[],geometryFailures:[],maxMidEntryDifferencePips:0};
 for(const t of trades){const base:any={trade_number:t.n,direction:'LONG',tv_entry_timestamp:t.entryWall,resolved_utc_entry:new Date(t.entryMs).toISOString(),tv_exit_timestamp:t.exitWall,resolved_utc_exit:new Date(t.exitMs).toISOString(),tv_entry_price:t.entry,tv_exit_price:t.exit,tv_exit_reason:t.exitLabel};const i=index.get(t.entryMs);if(i==null||a14[i]==null||e20[i]==null||e50[i]==null||e20[i-3]==null){rows.push({...base,matched:false,unmatched_reason:i==null?'NO_H1_ORIGIN_CANDLE':'INDICATOR_WARMUP_UNAVAILABLE'});continue;}const q=h1[i],entryMid=mid[i].c,risk=a14[i]!,stop=entryMid-risk,target=entryMid+2*risk,score=(e20[i]!>e50[i]! ?1:e20[i]!<e50[i]!?-1:0)+(entryMid>e20[i]! ?1:entryMid<e20[i]!?-1:0)+(e20[i]!>e20[i-3]! ?1:e20[i]!<e20[i-3]!?-1:0)+(entryMid>mid[i-3].c?1:entryMid<mid[i-3].c?-1:0);const missing:number[]=[];for(let at=t.entryMs+H;at<t.entryMs+4*H;at+=M)if(!minutes.has(at))missing.push(at);if(missing.length){rows.push({...base,oanda_mid_entry:entryMid,oanda_bid_entry:q.bc,oanda_ask_entry:q.ac,atr14:risk,initial_risk_pips:risk*PIP,consensus_score:score,original_stop:stop,original_target:target,matched:false,unmatched_reason:`M1_GAP_${new Date(missing[0]).toISOString()}_${missing.length}_MINUTES`});continue;}
  let midExit:number|null=null,execExit:number|null=null,midReason='',execReason='',ambMid=false,ambExec=false,exitQ:Candle|null=null;
  for(let at=t.entryMs+H;at<t.entryMs+4*H;at+=M){const z=minutes.get(at)!;const mh=(z.bh+z.ah)/2,ml=(z.bl+z.al)/2,mo=(z.bo+z.ao)/2;const mS=ml<=stop,mT=mh>=target,eS=z.bl<=stop,eT=z.bh>=target;if(midExit==null&&(mS||mT)){ambMid=mS&&mT;midExit=mS?(mo<=stop?mo:stop):(mo>=target?mo:target);midReason=ambMid?'M1_AMBIGUOUS_STOP_FIRST':mS?'SL':'TP';}if(execExit==null&&(eS||eT)){ambExec=eS&&eT;execExit=eS?(z.bo<=stop?z.bo:stop):(z.bo>=target?z.bo:target);execReason=ambExec?'M1_AMBIGUOUS_STOP_FIRST':eS?'SL':'TP';}if(midExit!=null&&execExit!=null){exitQ=z;break;}}
  if(midExit==null||execExit==null){const z=minutes.get(t.entryMs+4*H-M)!;if(midExit==null){midExit=(z.bc+z.ac)/2;midReason='TIME';}if(execExit==null){execExit=z.bc;execReason='TIME';}exitQ=z;}
  const tvR=(t.exit-t.entry)/risk,midR=(midExit-entryMid)/risk,execR=(execExit-q.ac)/risk;const expected=t.exitLabel==='TIME_EXIT'?'TIME':tvR>0?'TP':'SL';parity.maxMidEntryDifferencePips=Math.max(parity.maxMidEntryDifferencePips,Math.abs(entryMid-t.entry)*PIP);if(score<3)parity.consensusFailures.push({trade:t.n,score});if(t.exitLabel==='TP_OR_SL'){const g=Math.abs(t.exit-t.entry)/risk;if(g<.985||g>2.015)parity.geometryFailures.push({trade:t.n,geometryR:g});}
  rows.push({...base,oanda_mid_entry:entryMid,oanda_bid_entry:q.bc,oanda_ask_entry:q.ac,entry_spread_pips:(q.ac-q.bc)*PIP,atr14:risk,initial_risk_pips:risk*PIP,original_stop:stop,original_target:target,consensus_score:score,oanda_mid_exit:midExit,oanda_bid_exit:exitQ!.bc,oanda_ask_exit:exitQ!.ac,exit_spread_pips:(exitQ!.ac-exitQ!.bc)*PIP,mid_result_r:midR,exec_result_r:execR,execution_drag_r:midR-execR,mid_exit_reason:midReason,exec_exit_reason:execReason,m1_ambiguous_mid:ambMid,m1_ambiguous_exec:ambExec,spread_changed_outcome:expected!==execReason.replace('M1_AMBIGUOUS_STOP_FIRST','SL'),matched:true,unmatched_reason:''});
 }
 const matched=rows.filter(x=>x.matched),unmatched=rows.filter(x=>!x.matched),mr=matched.map(x=>x.mid_result_r),er=matched.map(x=>x.exec_result_r),midStats=stats(mr),execStats=stats(er),drag=matched.map(x=>x.execution_drag_r);const exits=['TP','SL','TIME'].map(reason=>{const z=matched.filter(x=>x.exec_exit_reason===reason||(reason==='SL'&&x.exec_exit_reason==='M1_AMBIGUOUS_STOP_FIRST'));return{exit:reason,count:z.length,dragTotal:sum(z.map(x=>x.execution_drag_r)),dragAverage:avg(z.map(x=>x.execution_drag_r))};});const years=['2023','2024','2025','2026'].map(year=>{const z=matched.filter(x=>x.resolved_utc_entry.startsWith(year)).map(x=>x.exec_result_r),s=stats(z);return{year,...s,status:yearStatus(s.expectancy)};});
 const columns=['trade_number','direction','tv_entry_timestamp','resolved_utc_entry','tv_exit_timestamp','resolved_utc_exit','tv_entry_price','oanda_mid_entry','oanda_bid_entry','oanda_ask_entry','entry_spread_pips','atr14','initial_risk_pips','consensus_score','original_stop','original_target','tv_exit_price','oanda_mid_exit','oanda_bid_exit','oanda_ask_exit','exit_spread_pips','mid_result_r','exec_result_r','execution_drag_r','tv_exit_reason','mid_exit_reason','exec_exit_reason','m1_ambiguous_mid','m1_ambiguous_exec','spread_changed_outcome','matched','unmatched_reason'];writeCsv('matched_trades.csv',matched,columns);writeCsv('unmatched_trades.csv',unmatched,columns);writeCsv('exec_trades.csv',matched,columns);
 const result={generated_at:new Date().toISOString(),status:'RESEARCH_ONLY_PAPER_ONLY',instrument:INSTRUMENT,cohort:{trades:216,wins:112,losses:104,wr:51.85,source:path.basename(SOURCE),matched:matched.length,unmatched:unmatched.length,resolved_executable:matched.length},timezone:{chart_timezone:'America/New_York',all_at_0600_utc:trades.filter(x=>new Date(x.entryMs).getUTCHours()===6).length},parity,mid:{...midStats,maxDrawdown:drawdown(mr)},exec:{...execStats,maxDrawdown:drawdown(er)},cost_drag:{average_r_per_trade:avg(drag),total_r:sum(drag),by_exit:exits},m1_ambiguity:{exec_count:matched.filter(x=>x.m1_ambiguous_exec).length,mid_count:matched.filter(x=>x.m1_ambiguous_mid).length,method:'same-minute TP and SL touches are conservatively STOP_FIRST'},years,classification:classify(execStats.expectancy),cost_verdict:execStats.expectancy>0?'SURVIVES_COSTS':'FAILS_COSTS',confirmations:['NO RULE CHANGE','NO NEW SIGNAL COHORT','NO DEPLOYMENT','NO BROKER ORDERS']};fs.writeFileSync(path.join(BASE,'RESULTS.json'),JSON.stringify(result,null,2));
 const table=(x:any,dd:number)=>`| ${x.n} | ${x.wins} | ${x.losses} | ${fmt(x.wr,2)}% | ${fmt(x.pf,3)} | ${fmt(x.total)}R | ${fmt(x.expectancy)}R | ${fmt(x.averageWinner)}R | ${fmt(x.averageLoser)}R | ${fmt(dd)}R |`;const report=['# GBPNZD 06UTC Bull Consensus V1 — frozen TradingView cohort executable validation','',`> **${result.classification} · ${result.cost_verdict} · RESEARCH_ONLY · PAPER_ONLY**`,'','## Cohort parity','',`- TradingView: **216** trades; **112** wins; **104** losses; **51.85%** WR.`,`- Matched: **${matched.length} / 216**. Unmatched: **${unmatched.length}**. Resolved executable: **${matched.length}**.`,`- DST-aware America/New_York resolution: **${result.timezone.all_at_0600_utc}/216** entries resolve to 06:00 UTC. No OANDA-derived signals were generated.`,`- OANDA H1 midpoint parity: max entry difference ${fmt(parity.maxMidEntryDifferencePips,3)} pips; consensus failures ${parity.consensusFailures.length}; geometry flags ${parity.geometryFailures.length}.`,'','## Results','', '| Replay | N | Wins | Losses | WR | PF | Total R | Expectancy | Avg win | Avg loss | Max DD |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|',`| MID |${table(midStats,drawdown(mr)).slice(1)}`,`| EXEC |${table(execStats,drawdown(er)).slice(1)}`,'','## Cost drag','',`- Average: **${fmt(avg(drag))}R/trade**. Total: **${fmt(sum(drag))}R**.`,`- By executable exit: ${exits.map(x=>`${x.exit} ${x.count}: ${fmt(x.dragTotal)}R total / ${fmt(x.dragAverage)}R avg`).join('; ')}.`,`- M1 ambiguity: EXEC **${result.m1_ambiguity.exec_count}**, MID **${result.m1_ambiguity.mid_count}**; a same-minute TP/SL touch is flagged and resolved conservatively stop-first.`,'','## Year stability — EXEC','', '| Year | N | WR | PF | Total R | Expectancy | Status |','|---|---:|---:|---:|---:|---:|---|',...years.map(x=>`| ${x.year} | ${x.n} | ${fmt(x.wr,2)}% | ${fmt(x.pf,3)} | ${fmt(x.total)}R | ${fmt(x.expectancy)}R | ${x.status} |`),'','## Final decision','',`- Classification: **${result.classification}** (EXEC expectancy ${fmt(execStats.expectancy)}R/trade).`,`- Cost verdict: **${result.cost_verdict}**.`,`- Candidate decision: **${execStats.expectancy>=.15?'freeze as a cost-surviving paper research candidate':execStats.expectancy>=.10?'freeze as a cost-surviving paper research candidate':execStats.expectancy>=.05?'freeze only as a marginal research candidate':'reject'}**.`,`- Explicit confirmations: **NO RULE CHANGE · NO NEW SIGNAL COHORT · NO DEPLOYMENT · NO BROKER ORDERS**.`,``, 'Method: authoritative CSV cohort only; OANDA Practice completed H1/M1 MBA data; frozen geometry is OANDA H1 midpoint close ± one/two ATR14; MID exits use midpoint and EXEC enters ASK with BID TP/SL/TIME exits. No second spread charge.'].join('\n');fs.writeFileSync(path.join(BASE,'FINAL_REPORT.md'),report);console.log(`GBPNZD replay complete: ${matched.length}/216 matched; EXEC ${fmt(execStats.expectancy)}R, ${result.classification}, ${result.cost_verdict}`);
}
main().catch(error=>{console.error(error);process.exit(1)});
